--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local LANG = {
  ["ConCommand.Drop"] = "Smid :item:",
  ["ConCommand.DropAll"] = "Smid :amount:x :item:",
  ["ConCommand.Destroy"] = "Ødelage :amount:x :item:",
  ["ConCommand.Destroy.Popup.Title"] = "Ødelæg :item:",
  ["ConCommand.Destroy.Popup.Desc"] = "Er du sikker på, at du vil ødelægge:item:?",
  ["ConCommand.Destroy.Popup.Yes"] = "Ja",
  ["ConCommand.Destroy.Popup.No"] = "Nej",

  ["ChatCommand.Holster.Unable"] = "Du kan ikke hylstre dette våben på grund af din begrænsede lagerplads",
  ["ChatCommand.Blacklisted"] = "Dette objekt kan ikke puttes i dit inventar",

  ["Bank.Title"] = "XeninInventory - Bank",
  ["XeninInventory.Title"] = "Inventory",


  ["XeninInventory.Tabs.XeninInventory"] = "INVENTORY",


  ["XeninInventory.Popup.Equip"] = "Udstyr",
  ["XeninInventory.Popup.Drop"] = "Smid",
  ["XeninInventory.Popup.Drop All"] = "Smid Alt",
  ["XeninInventory.Popup.Destroy"] = "Ødelægge",
  ["XeninInventory.Popup.Use"] = "Brug",
  ["XeninInventory.Popup.Drop Amount"] = "Smid beløb",

  ["XeninInventory.Popup.DropAmount.Error.Invalid"] = "Ugyldigt antal?",
  ["XeninInventory.Popup.DropAmount.Error.TooLow"] = "Too low of a number",
  ["XeninInventory.Popup.DropAmount.Error.TooHigh"] = "Du kan ikke have droppe så mange, fordi du ikke har så mange!",


  ["XeninInventory.Actions.Equip"] = "UDSTYR",
  ["XeninInventory.Actions.Drop"] = "SMID",
  ["XeninInventory.Actions.Drop All"] = "DROP ALLE",
  ["XeninInventory.Actions.Destroy"] = "ØDELÆGGE",
  ["XeninInventory.Actions.Use"] = "BRUG",
  ["XeninInventory.Actions.Drop Amount"] = "SMID MÆNGDE",


  ["XeninInventory.Field.Amount"] = "x:amount:",
  ["XeninInventory.Field.MaxAmount"] = "max x:amount:",

  ["XeninInventory.XeninInventory.Search"] = "Søg efter en vare",

  ["XeninInventory.XeninInventory.Unsorted"] = "Usorteret",
  ["XeninInventory.XeninInventory.Alphabetically"] = "Alfabetisk",
  ["XeninInventory.XeninInventory.WorstToBest"] = "Værst at bedst",
  ["XeninInventory.XeninInventory.BestToWorst"] = "Bedst til værst",

  ["XeninInventory.Shipment.Desc"] = ":amount: våben tilbage",

  ["XeninInventory.Pickup.Markup"] = ":font::color:Press :/color::rarityColor::modifierKey: + :key::/color: at tilføje :name: til din beholdning:/color::/font:",
  ["XeninInventory.Pickup"] = "Tryk på :modifierKey: +:key:  at tilføje :name: til din beholdning",
  ["XeninInventory.Money"] = ":money:",

  ["Admin.Title"] = "XeninInventory Admin",
  ["Admin.Tabs.Management"] = "LEDELSE",
  ["Admin.NotAdmin"] = "Du skal være en administrator for at åbne dette!",

  ["Admin.Management.Loading"] = "Indlæser",
  ["Admin.Management.Search"] = "Søg efter navn / SteamID(64)",
  ["Admin.Management.Searching"] = "Søger",
  ["Admin.Management.Online"] = "Online",
  ["Admin.Management.Offline"] = "Offline",
  ["Admin.Management.OpenInventory"] = "Åben beholdning",

  ["Admin.Player.Title"] = "Spillerinventar",
  ["Admin.Player.Tabs.XeninInventory"] = "INVENTAR",
  ["Admin.Player.Tabs.Bank"] = "BANK",
  ["Admin.Player.Items"] = ":items: items",
  ["Admin.Player.Clear.XeninInventory"] = "Ryd inventar",
  ["Admin.Player.Clear.Bank"] = "Ryd bank",
  ["Admin.Player.Clear.Popup.Text"] = "Er du sikker på, at du vil rydde disse spillere: type :? Dette kan ikke fortrydes!",
  ["Admin.Player.Clear.Popup.Yes"] = "Ja, klart",
  ["Admin.Player.Clear.Popup.No"] = "Nej",

  ["Admin.Clear.Slot"] = "Dine :type: slot nummer :id: er blevet ryddet af en administrator",
  ["Admin.Clear"] = "Dine :type: er blevet ryddet af en administrator"
}

XeninInventory:CreateLanguage("Danish", LANG)
