--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local LANG = {
  ["ConCommand.Drop"] = "Dropped :item:",
  ["ConCommand.DropAll"] = "Dropped :amount:x :item:",
  ["ConCommand.Destroy"] = "Destroyed :amount:x :item:",
  ["ConCommand.Destroy.Popup.Title"] = "Destroy :item:",
  ["ConCommand.Destroy.Popup.Desc"] = "Are you sure you want to destroy :item:?",
  ["ConCommand.Destroy.Popup.Yes"] = "Yes",
  ["ConCommand.Destroy.Popup.No"] = "No",

  ["ChatCommand.Holster.Unable"] = "You are unable to holster this weapon due to your limited inventory space",
  ["ChatCommand.Blacklisted"] = "This item is blacklisted",
  ["ChatCommand.AccessRestricted"] = "Your access to your inventory is currently restricted.",

  ["Bank.Title"] = "Inventory - Bank",
  ["XeninInventory.Title"] = "Inventory",


  ["XeninInventory.Tabs.XeninInventory"] = "INVENTORY",


  ["XeninInventory.Popup.Equip"] = "Equip",
  ["XeninInventory.Popup.Drop"] = "Drop",
  ["XeninInventory.Popup.Drop All"] = "Drop All",
  ["XeninInventory.Popup.Destroy"] = "Destroy",
  ["XeninInventory.Popup.Use"] = "Use",
  ["XeninInventory.Popup.Drop Amount"] = "Drop Amount",

  ["XeninInventory.Popup.DropAmount.Error.Invalid"] = "Invalid number?",
  ["XeninInventory.Popup.DropAmount.Error.TooLow"] = "Too low of a number",
  ["XeninInventory.Popup.DropAmount.Error.TooHigh"] = "You can't have drop that many because you don't have that many!",


  ["XeninInventory.Actions.Equip"] = "EQUIP",
  ["XeninInventory.Actions.Drop"] = "DROP",
  ["XeninInventory.Actions.Drop All"] = "DROP ALL",
  ["XeninInventory.Actions.Destroy"] = "DESTROY",
  ["XeninInventory.Actions.Use"] = "USE",
  ["XeninInventory.Actions.Drop Amount"] = "DROP AMOUNT",


  ["XeninInventory.Field.Amount"] = "x:amount:",
  ["XeninInventory.Field.MaxAmount"] = "max x:amount:",

  ["XeninInventory.XeninInventory.Search"] = "Search for an item",

  ["XeninInventory.XeninInventory.Unsorted"] = "Unsorted",
  ["XeninInventory.XeninInventory.Alphabetically"] = "Alphabetically",
  ["XeninInventory.XeninInventory.WorstToBest"] = "Worst to best",
  ["XeninInventory.XeninInventory.BestToWorst"] = "Best to worst",

  ["XeninInventory.Shipment.Desc"] = ":amount: weapons left",

  ["XeninInventory.Pickup.Markup"] = ":font::color:Press :/color::rarityColor::modifierKey: + :key::/color: to add :name: to your inventory:/color::/font:",
  ["XeninInventory.Pickup"] = "Press :modifierKey: + :key: to add :name: to your inventory",
  ["XeninInventory.Money"] = ":money:",

  ["Admin.Title"] = "Inventory Admin",
  ["Admin.Tabs.Management"] = "MANAGEMENT",
  ["Admin.NotAdmin"] = "You need to be an inventory admin to open this!",

  ["Admin.Management.Loading"] = "Loading",
  ["Admin.Management.Search"] = "Search by name/SteamID(64)",
  ["Admin.Management.Searching"] = "Searching",
  ["Admin.Management.Online"] = "Online",
  ["Admin.Management.Offline"] = "Offline",
  ["Admin.Management.OpenInventory"] = "Open Inventory",

  ["Admin.Player.Title"] = "Player Inventory",
  ["Admin.Player.Tabs.XeninInventory"] = "INVENTORY",
  ["Admin.Player.Tabs.Bank"] = "BANK",
  ["Admin.Player.Items"] = ":items: items",
  ["Admin.Player.Clear.XeninInventory"] = "Clear Inventory",
  ["Admin.Player.Clear.Bank"] = "Clear Bank",
  ["Admin.Player.Clear.Popup.Text"] = "Are you sure you want to clear this players :type:? This cannot be undone!",
  ["Admin.Player.Clear.Popup.Yes"] = "Yes, clear",
  ["Admin.Player.Clear.Popup.No"] = "No",

  ["Admin.Clear.Slot"] = "Your :type: slot number :id: have been cleared by an admin",
  ["Admin.Clear"] = "Your :type: have been cleared by an admin"
}

XeninInventory:CreateLanguage("English", LANG)
