--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local LANG = {
  ["ConCommand.Drop"] = "Laché :item:",
  ["ConCommand.DropAll"] = "Laché :amount:x :item:",
  ["ConCommand.Destroy"] = "Détruit :amount:x :item:",
  ["ConCommand.Destroy.Popup.Title"] = "Détruire :item:",
  ["ConCommand.Destroy.Popup.Desc"] = "Êtes-vous sûr de vouloir détruire : :item:?",
  ["ConCommand.Destroy.Popup.Yes"] = "Oui",
  ["ConCommand.Destroy.Popup.No"] = "Non",

  ["ChatCommand.Holster.Unable"] = "Vous ne pouvez pas mettre cette arme dans l'étui en raison de votre espace d'inventaire limité",
  ["ChatCommand.Blacklisted"] = "Cet article est sur liste noire !",


  ["Bank.Title"] = "Inventaire - Banque",
  ["XeninInventory.Title"] = "Inventaire",


  ["XeninInventory.Tabs.XeninInventory"] = "INVENTAIRE",


  ["XeninInventory.Popup.Equip"] = "Equiper",
  ["XeninInventory.Popup.Drop"] = "Lacher",
  ["XeninInventory.Popup.Drop All"] = "Lacher tout",
  ["XeninInventory.Popup.Destroy"] = "Détruire",
  ["XeninInventory.Popup.Use"] = "Utiliser",
  ["XeninInventory.Popup.Drop Amount"] = "Lacher un montant",

  ["XeninInventory.Popup.DropAmount.Error.Invalid"] = "Numéro invalide ?",
  ["XeninInventory.Popup.DropAmount.Error.TooLow"] = "Trop bas d'un nombre",
  ["XeninInventory.Popup.DropAmount.Error.TooHigh"] = "Vous ne pouvez pas en laisser tomber autant parce que vous n'en avez pas asser !",


  ["XeninInventory.Actions.Equip"] = "Equiper",
  ["XeninInventory.Actions.Drop"] = "Lacher",
  ["XeninInventory.Actions.Drop All"] = "Tout lacher",
  ["XeninInventory.Actions.Destroy"] = "Détruire",
  ["XeninInventory.Actions.Use"] = "Utiliser",
  ["XeninInventory.Actions.Drop Amount"] = "Lacher un montant",


  ["XeninInventory.Field.Amount"] = "x:amount:",
  ["XeninInventory.Field.MaxAmount"] = "max x:amount:",

  ["XeninInventory.XeninInventory.Search"] = "Rechercher un article",


  ["XeninInventory.XeninInventory.Unsorted"] = "non trié",
  ["XeninInventory.XeninInventory.Alphabetically"] = "Alphabétiquement",
  ["XeninInventory.XeninInventory.WorstToBest"] = "Du pire au meilleur",
  ["XeninInventory.XeninInventory.BestToWorst"] = "Du meilleur au pire",


  ["XeninInventory.Shipment.Desc"] = ":amount: armes à gauche",

  ["XeninInventory.Pickup.Markup"] = ":font::color:Press :/color::rarityColor::modifierKey: + :key::/color: ajouter :name: à votre inventaire:/color::/font:",
  ["XeninInventory.Pickup"] = "Appuyer :modifierKey: + :key: ajouter :name: à votre inventaire",
  ["XeninInventory.Money"] = ":money:",

  ["Admin.Title"] = "Inventaire Admin",
  ["Admin.Tabs.Management"] = "GESTION",
  ["Admin.NotAdmin"] = "Vous devez être un administrateur d'inventaire pour ouvrir ceci !",

  ["Admin.Management.Loading"] = "Chargement...",
  ["Admin.Management.Search"] = "Chercher par Nom/SteamID64",
  ["Admin.Management.Searching"] = "Recherche",
  ["Admin.Management.Online"] = "En Ligne",
  ["Admin.Management.Offline"] = "Hors Ligne",
  ["Admin.Management.OpenInventory"] = "Ouvrir Inventaire",

  ["Admin.Player.Title"] = "Inventaire Joueur",
  ["Admin.Player.Tabs.XeninInventory"] = "INVENTAIRE",
  ["Admin.Player.Tabs.Bank"] = "BANQUE",

  ["Admin.Player.Items"] = ":items: items",

  ["Admin.Player.Clear.XeninInventory"] = "Rénitialiser l'inventaire",
  ["Admin.Player.Clear.Bank"] = "Rénitialiser l'inventaire banque",
  ["Admin.Player.Clear.Popup.Text"] = "êtes-vous sûr de vouloir rénitialiser l'inventaire de : :type: ? C'est une action irréversible",
  ["Admin.Player.Clear.Popup.Yes"] = "Oui",
  ["Admin.Player.Clear.Popup.No"] = "Non",

  ["Admin.Clear.Slot"] = "Votre :type: numéro d'emplacement :id: ont été effacés par un administrateur",
  ["Admin.Clear"] = "Votre :type: ont été effacés par un administrateur"
}


XeninInventory:CreateLanguage("French", LANG)
