--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local LANG = {
  ["ConCommand.Drop"] = "Dropeado :item:",
  ["ConCommand.DropAll"] = "Dropeado :amount:x :item:",
  ["ConCommand.Destroy"] = "Destruido :amount:x :item:",
  ["ConCommand.Destroy.Popup.Title"] = "Destruir :item:",
  ["ConCommand.Destroy.Popup.Desc"] = "¿Estás seguro de que quieres destruir :item:?",
  ["ConCommand.Destroy.Popup.Yes"] = "Sí",
  ["ConCommand.Destroy.Popup.No"] = "No",

  ["ChatCommand.Holster.Unable"] = "No puedes enfundar esta arma debido a tu espacio limitado en el inventario.",
  ["ChatCommand.Blacklisted"] = "Este artículo está en la lista negra",
  ["ChatCommand.AccessRestricted"] = "Su acceso a su inventario está actualmente restringido.",

  ["Bank.Title"] = "Inventario - Banco",
  ["XeninInventory.Title"] = "Inventario",


  ["XeninInventory.Tabs.XeninInventory"] = "INVENTARIO",


  ["XeninInventory.Popup.Equip"] = "Equipar",
  ["XeninInventory.Popup.Drop"] = "Soltar",
  ["XeninInventory.Popup.Drop All"] = "Soltar todo",
  ["XeninInventory.Popup.Destroy"] = "Destruir",
  ["XeninInventory.Popup.Use"] = "Usar",
  ["XeninInventory.Popup.Drop Amount"] = "Soltar Cantidad",

  ["XeninInventory.Popup.DropAmount.Error.Invalid"] = "¿Número invalido?",
  ["XeninInventory.Popup.DropAmount.Error.TooLow"] = "Un número demasiado bajo",
  ["XeninInventory.Popup.DropAmount.Error.TooHigh"] = "¡No puedes dejar caer tantos porque no tienes tantos!",


  ["XeninInventory.Actions.Equip"] = "EQUIPAR",
  ["XeninInventory.Actions.Drop"] = "SOLTAR",
  ["XeninInventory.Actions.Drop All"] = "DEJAR TODO",
  ["XeninInventory.Actions.Destroy"] = "DESTRUIR",
  ["XeninInventory.Actions.Use"] = "USAR",
  ["XeninInventory.Actions.Drop Amount"] = "SOLTAR CANTIDAD",


  ["XeninInventory.Field.Amount"] = "x:amount:",
  ["XeninInventory.Field.MaxAmount"] = "x:amount: máximo",

  ["XeninInventory.XeninInventory.Search"] = "Buscar un artículo",

  ["XeninInventory.XeninInventory.Unsorted"] = "Sin clasificar",
  ["XeninInventory.XeninInventory.Alphabetically"] = "Alfabéticamente",
  ["XeninInventory.XeninInventory.WorstToBest"] = "Peor a mejor",
  ["XeninInventory.XeninInventory.BestToWorst"] = "Mejor a peor",

  ["XeninInventory.Shipment.Desc"] = ":amount: armas restantes",

  ["XeninInventory.Pickup.Markup"] = ":font::color:Presiona :/color::rarityColor::modifierKey: + :key::/color: para agregar :name: a tu inventario:/color::/font:",
  ["XeninInventory.Pickup"] = "Presiona :modifierKey: + :key: para agregar :name: a tu inventario",
  ["XeninInventory.Money"] = ":money:",

  ["Admin.Title"] = "Inventario Admin",
  ["Admin.Tabs.Management"] = "ADMINISTRACIÓN",
  ["Admin.NotAdmin"] = "¡Tienes que ser un administrador para abrir esto!",

  ["Admin.Management.Loading"] = "Cargando",
  ["Admin.Management.Search"] = "Buscar por nombre/SteamID(64)",
  ["Admin.Management.Searching"] = "buscando",
  ["Admin.Management.Online"] = "En línea",
  ["Admin.Management.Offline"] = "Desconectado",
  ["Admin.Management.OpenInventory"] = "Abrir el inventario",

  ["Admin.Player.Title"] = "Inventario de jugador",
  ["Admin.Player.Tabs.XeninInventory"] = "INVENTARIO",
  ["Admin.Player.Tabs.Bank"] = "BANCO",
  ["Admin.Player.Items"] = ":items: items",
  ["Admin.Player.Clear.XeninInventory"] = "Borrar inventario",
  ["Admin.Player.Clear.Bank"] = "Borrar banco",
  ["Admin.Player.Clear.Popup.Text"] = "¿Estás seguro de que quieres borrar el :type: de este jugador? ¡Esto no se puede deshacer!",
  ["Admin.Player.Clear.Popup.Yes"] = "Sí, borrar",
  ["Admin.Player.Clear.Popup.No"] = "No",

  ["Admin.Clear.Slot"] = "Tu slot :type: numero :id: ha sido borrado por un administrador",
  ["Admin.Clear"] = "Tu :type: ha sido borrado por un administrador"
}

XeninInventory:CreateLanguage("Spanish", LANG)
