--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local LANG = {
  ["ConCommand.Drop"] = ":item: eşyası yere bırakıldı",
  ["ConCommand.DropAll"] = ":amount: adet :item: eşyası yere bırakıldı",
  ["ConCommand.Destroy"] = ":amount: adet :item: eşyası silindi",
  ["ConCommand.Destroy.Popup.Title"] = ":item: eşyasını sil",
  ["ConCommand.Destroy.Popup.Desc"] = ":item: bu eşyayı silmek istediğinizden emin misiniz?",
  ["ConCommand.Destroy.Popup.Yes"] = "Evet",
  ["ConCommand.Destroy.Popup.No"] = "Hayır",

  ["ChatCommand.Holster.Unable"] = "Sınırlı envanter alanınız nedeniyle bu silahı tutamazsınız.",
  ["ChatCommand.Blacklisted"] = "Bu eşya karalistede",
  ["ChatCommand.AccessRestricted"] = "Envanterinize erişiminiz şu anda kısıtlı.",

  ["Bank.Title"] = "Banka Deposu",
  ["XeninInventory.Title"] = "Envanter",


  ["XeninInventory.Tabs.XeninInventory"] = "ENVANTER",


  ["XeninInventory.Popup.Equip"] = "Kuşan",
  ["XeninInventory.Popup.Drop"] = "Bırak",
  ["XeninInventory.Popup.Drop All"] = "Hepsini Bırak",
  ["XeninInventory.Popup.Destroy"] = "Sil",
  ["XeninInventory.Popup.Use"] = "Kullan",
  ["XeninInventory.Popup.Drop Amount"] = "Sayıyla Bırak",

  ["XeninInventory.Popup.DropAmount.Error.Invalid"] = "Bilinmeyen sayı?",
  ["XeninInventory.Popup.DropAmount.Error.TooLow"] = "Sayı çok düşük",
  ["XeninInventory.Popup.DropAmount.Error.TooHigh"] = "O kadar çok düşüremezsin çünkü o kadar çok yok!",


  ["XeninInventory.Actions.Equip"] = "KUŞAN",
  ["XeninInventory.Actions.Drop"] = "BIRAK",
  ["XeninInventory.Actions.Drop All"] = "HEPSİNİ BIRAK",
  ["XeninInventory.Actions.Destroy"] = "SİL",
  ["XeninInventory.Actions.Use"] = "KULLAN",
  ["XeninInventory.Actions.Drop Amount"] = "SAYIYLA BIRAK",


  ["XeninInventory.Field.Amount"] = ":amount:",
  ["XeninInventory.Field.MaxAmount"] = "maks :amount:",

  ["XeninInventory.XeninInventory.Search"] = "Bir eşya ara",

  ["XeninInventory.XeninInventory.Unsorted"] = "Sınıflandırılmamış",
  ["XeninInventory.XeninInventory.Alphabetically"] = "Alfabetik",
  ["XeninInventory.XeninInventory.WorstToBest"] = "Kötüden iyiye",
  ["XeninInventory.XeninInventory.BestToWorst"] = "İyiden kötüye",

  ["XeninInventory.Shipment.Desc"] = ":amount: silah kaldı",

  ["XeninInventory.Pickup.Markup"] = ":font::color: :/color::rarityColor::modifierKey: + :key::/color: tuşuna basarak :name: eşyasını envanterine alabilirsin :/color::/font:",
  ["XeninInventory.Pickup"] = ":modifierKey: + :key: tuşuna basarak :name: eşyasını envanterine alabilirsin",
  ["XeninInventory.Money"] = ":money:",

  ["Admin.Title"] = "Inventory Admin",
  ["Admin.Tabs.Management"] = "YÖNETİM",
  ["Admin.NotAdmin"] = "You need to be an inventory admin to open this!",

  ["Admin.Management.Loading"] = "Yükleniyor",
  ["Admin.Management.Search"] = "Search by name/SteamID(64)",
  ["Admin.Management.Searching"] = "Searching",
  ["Admin.Management.Online"] = "Çevrimiçi",
  ["Admin.Management.Offline"] = "Çevrimdışı",
  ["Admin.Management.OpenInventory"] = "Envanteri Aç",

  ["Admin.Player.Title"] = "Oyuncu Envanteri",
  ["Admin.Player.Tabs.XeninInventory"] = "ENVANTER",
  ["Admin.Player.Tabs.Bank"] = "BANKA DEPOSU",
  ["Admin.Player.Items"] = ":items: items",
  ["Admin.Player.Clear.XeninInventory"] = "Envanteri Temizle",
  ["Admin.Player.Clear.Bank"] = "Banka Deposunu Temizle",
  ["Admin.Player.Clear.Popup.Text"] = "Are you sure you want to clear this players :type:? Bu işlemi geri alamazsın!",
  ["Admin.Player.Clear.Popup.Yes"] = "Evet",
  ["Admin.Player.Clear.Popup.No"] = "Hayır",

  ["Admin.Clear.Slot"] = "Your :type: slot number :id: have been cleared by an admin",
  ["Admin.Clear"] = "Your :type: have been cleared by an admin"
}

XeninInventory:CreateLanguage("Turkish", LANG)
