zpiz = zpiz or {}
zpiz.materials = zpiz.materials or {}
zpiz.materials["zpiz_button"] = Material("materials/zerochain/zpizmak/ui/zpizmak_button.png", "smooth")
zpiz.materials["zpiz_circle"] = Material("materials/zerochain/zpizmak/ui/zpizmak_circle.png", "smooth")
zpiz.materials["zpiz_ingredient_top"] = Material("materials/zerochain/zpizmak/ui/zpizmak_ingredient_top.png", "smooth")
zpiz.materials["zpiz_arrow"] = Material("materials/zerochain/zpizmak/ui/zpizmak_arrow.png", "smooth")
zpiz.materials["zpiz_clock_base"] = Material("materials/zerochain/zpizmak/ui/zpizmak_clock_base.png", "smooth")
zpiz.materials["zpiz_clock_pointer"] = Material("materials/zerochain/zpizmak/ui/zpizmak_clock_pointer.png", "smooth")
zpiz.materials["zpiz_ui_panel"] = Material("materials/zerochain/zpizmak/ui/zpizmak_ui_panel.png", "smooth")

zpiz.colors = zpiz.colors or {}
zpiz.colors["blue01"] = Color(108, 137, 174, 255)
zpiz.colors["orange01"] = Color(179, 135, 84, 255)
zpiz.colors["burned"] = Color(116, 81, 61, 255)
zpiz.colors["black01"] = Color(5, 5, 5, 255)
zpiz.colors["black02"] = Color(0, 0, 0, 100)
zpiz.colors["red01"] = Color(160, 0, 0)
zpiz.colors["brown01"] = Color(200, 150, 119)
zpiz.colors["brown02"] = Color(91, 61, 43)
zpiz.colors["brown03"] = Color(48, 32, 23)
zpiz.colors["brown04"] = Color(238, 207, 167)
zpiz.colors["brown05"] = Color(192, 125, 46)
