--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local ITEM = XeninInventory:CreateItemV2()
ITEM:SetDescription(function(self, item, ent)
  local wep = weapons.Get(item.ent)
  if (!wep) then return "Unknown weapon?"end

  local tbl = {}
  local dmg = wep.Primary.Damage
  if dmg then
    tbl[#tbl + 1] = "Damage: " .. math.Round(dmg, 2)
  end
  local magSize = wep.Primary.ClipSize
  if magSize then
    local clipSize = (item.data and item.data.Clip1 or 0) or 0
    tbl[#tbl + 1] = "Clip: " .. clipSize .. "/" .. magSize
  end
  local rpm = wep.Primary.Delay
  if rpm then
    tbl[#tbl + 1] = "RPM: " .. math.Round(60 / rpm)
  end

  return tbl
end)

ITEM:AddEquip(function(self, ply, tbl)
  if CLIENT then return true end

  local ent = tbl.ent
  local wep = ply:Give(ent, true)
  ply:SelectWeapon(ent)

  if IsValid(wep) then
    local clip1 = tbl.data.Clip1
    local clip2 = tbl.data.Clip2

    if (clip1 and clip1 != -1) then
      wep:SetClip1(clip1)
    end
    if (clip2 and clip2 != -1) then
      wep:SetClip2(clip2)
    end
  end

  return true
end, function(self, ply, slot)
  local ent = slot.ent
  local data = slot.data
  local name = self:GetName(slot)

  return !ply:HasWeapon(ent), "You already have a(n) " .. name .. " equipped"
end)

ITEM:AddDrop(function(self, ply, ent, tbl, tr)
  local mdl = self:GetModel(tbl.ent)
  ent:SetModel(mdl)
  ent:SetWeaponClass(tbl.ent)
  ent.clip1 = tbl.data.Clip1
  ent.clip2 = tbl.data.Clip2
end)

ITEM:AddDrop(function(self, ply, ent, tbl, tr, amt)
  local mdl = self:GetModel(tbl.ent)
  ent:SetModel(mdl)
  ent:SetWeaponClass(tbl.ent)
  ent:Setamount(amt or 1)
  ent.clip1 = tbl.data.Clip1
  ent.clip2 = tbl.data.Clip2
end, ITEM.DROP_ALL)

function ITEM:GetData(ent)
  return {
    Clip1 = ent.clip1,
    Clip2 = ent.clip2
  }
end

function ITEM:GetName(tbl)
  local wep = weapons.Get(tbl.ent)
  if (!wep) then return tbl.ent end

  return wep.PrintName or tbl.ent
end

function ITEM:GetEntityClass(ent)
  return ent:GetWeaponClass()
end

function ITEM:GetEntityAmount(ent)
  return ent:Getamount()
end

ITEM:Register("spawned_weapon")
