--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local ITEM = XeninInventory:CreateItemV2()
ITEM.Name = "Muffin"
ITEM:SetMaxStack(1)
ITEM:SetModel("models/zerochain/props_weedfarm/zwf_muffin.mdl")
ITEM:SetDescription(function(self, tbl)
  if (tbl.data.WeedID != -1) then
    return "A tasty muffin with traces of weed"
  else
    return "A tasty muffin"
  end
end)

ITEM:AddDrop(function(self, ply, ent, tbl, tr)
  local data = tbl.data

  ent.WeedID = data.WeedID
  ent.WeedName = data.WeedName
  ent.WeedAmount = data.WeedAmount
  ent.WeedTHC = data.THC
  ent:SetColor(self:GetColor(tbl))
  if (ent.WeedID != -1) then
    ent:SetSkin(1)
  end
end)

function ITEM:GetData(ent)
  return {
    WeedID = ent.WeedID,
    WeedName = ent.WeedName,
    WeedAmount = ent.WeedAmount,
    THC = ent.WeedTHC
  }
end

function ITEM:GetSkin(tbl)
  if (tbl.data.WeedID != -1) then
    return 1
  end
end

function ITEM:GetColor(tbl)
  if tbl.data.WeedID then
    local plant = zwf.config.Plants[tbl.data.WeedID]
    if plant then
      return plant.color
    end
  else
    return HSVToColor(math.random(0, 360), 0.5, 0.85)
  end
end

function ITEM:GetVisualAmount(item)
  return item.data.WeedAmount
end

function ITEM:GetName(item)
  local ent = isentity(item)
  local weedName = ent and self.Name or item.data.WeedName
  local id = !ent and item.data.WeedID
  local str = weedName
  if id then
    local plant = zwf.config.Plants[id]
    if (plant and plant.name) then
      str = str .. " [" .. plant.name .. "]"
    end
  end

  return str
end

ITEM:Register("zwf_muffin")
