--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local ITEM = XeninInventory:CreateItemV2()
ITEM:SetMaxStack(1)
ITEM:SetModel("models/zerochain/props_weedfarm/zwf_jar.mdl")
ITEM:SetDescription("A jar of weed")

ITEM:AddDrop(function(self, ply, ent, tbl, tr)
  local data = tbl.data

  ent:SetPlantID(data.PlantID)
  ent:SetWeedName(data.WeedName)
  ent:SetWeedAmount(data.WeedAmount)
  ent:SetTHC(data.THC)

  ent:SetPerf_Time(data.Perf_Time)
  ent:SetPerf_Amount(data.Perf_Amount)
  ent:SetPerf_THC(data.Perf_THC)

  zwf.f.SetOwnerByID(ent, data.ZWFOwner)
end)

function ITEM:GetData(ent)
  return {
    PlantID = ent:GetPlantID(),
    WeedName = ent:GetWeedName(),
    WeedAmount = ent:GetWeedAmount(),
    THC = ent:GetTHC(),
    Perf_Time = ent:GetPerf_Time(),
    Perf_Amount = ent:GetPerf_Amount(),
    Perf_THC = ent:GetPerf_THC(),
    ZWFOwner = zwf.f.GetOwnerID(ent)
  }
end

function ITEM:GetVisualAmount(item)
  return item.data.WeedAmount
end

function ITEM:GetName(item)
  local ent = isentity(item)
  local weedName = ent and item:GetWeedName() or item.data.WeedName
  local plant = ent and item:GetPlantID() or item.data.PlantID
  plant = zwf.config.Plants[plant]
  plant = plant and plant.Name or "Unknown plant"

  return weedName .. " [" .. plant .. "]"
end


ITEM:Register("zwf_jar")
