--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local PANEL = {}

function PANEL:Init()
  if IsValid(XeninInventory.AdminFrame) then
    XeninInventory.AdminFrame:Remove()
  end

  XeninInventory.AdminFrame = self

  self.topNavbar = vgui.Create("Panel", self)
  self.topNavbar:Dock(TOP)

  self.navbar = vgui.Create("XeninUI.Navbar", self.topNavbar)
  self.navbar:Dock(FILL)
  self.navbar:SetBody(self)
  self.navbar:AddTab(XeninInventory:GetPhrase("Admin.Tabs.Management"), "XeninInventory.Admin.Management")
  self.navbar:AddTab("IMPORTER", "XeninInventory.Admin.Importer")

  self.navbar:SetActive(XeninInventory:GetPhrase("Admin.Tabs.Management"))
end

function PANEL:PerformLayout(w, h)
  self.BaseClass.PerformLayout(self, w, h)

  self.topNavbar:SetTall(56)
end
vgui.Register("XeninInventory.Admin", PANEL, "XeninUI.Frame")

concommand.Add("inventory_admin", function()
  local inv = LocalPlayer():XeninInventory()
  if (!XeninInventory:IsAdmin(LocalPlayer())) then
    inv:Message(XeninInventory:GetPhrase("Admin.Tabs.NotAdmin"))

    return
  end

  local frame = vgui.Create("XeninInventory.Admin")
  local width = math.min(ScrW(), XeninUI.Frame.Width)
  local height = math.min(ScrH(), XeninUI.Frame.Height + 100)
  frame:SetSize(width, height)
  frame:Center()
  frame:MakePopup()
  frame:SetTitle(XeninInventory:GetPhrase("Admin.Title"))
end)
