AAS = AAS or {}

--[[ If you want to add more category in the main menu you can just copy/past this 
    [YOUNEEDTOCHANGETHIS] = {    
        ["uniqueName"] = "Hat",
        ["material"] = Material("aas_materials/ass_icon_hat.png", "smooth"),
        ["margin"] = 0.006,
    }

    DON'T TOUCH THE CATEGORY OF adminMenu AND positionMenu please !
]]
AAS.Category = {
    ["mainMenu"] = {
        [1] = {
            ["uniqueName"] = "All",
            ["material"] = Material("aas_materials/ass_icon_all.png", "smooth"),
            ["all"] = true,
            ["margin"] = 0,
            ["bone"] = "ValveBiped.Bip01_Head1",
        },
        [2] = {
            ["uniqueName"] = "Hat",
            ["material"] = Material("aas_materials/ass_icon_hat.png", "smooth"),
            ["margin"] = 0.006,
            ["bone"] = "ValveBiped.Bip01_Head1",
        }, 
        [3] = {
            ["uniqueName"] = "Glasses",
            ["material"] = Material("aas_materials/ass_icon_glasses.png", "smooth"),
            ["margin"] = 0.005,
            ["bone"] = "ValveBiped.Bip01_Head1",
        },
        [4] = {
            ["uniqueName"] = "Face Mask",
            ["material"] = Material("aas_materials/aas_mask_2.png", "smooth"),
            ["margin"] = 0.008,
            ["bone"] = "ValveBiped.Bip01_Head1",
        },
        [5] = {
            ["uniqueName"] = "Mouse Mask",
            ["material"] = Material("aas_materials/ass_mask_1.png", "smooth"),
            ["margin"] = 0.008,
            ["bone"] = "ValveBiped.Bip01_Head1",
        },
        [6] = {
            ["uniqueName"] = "BackPack",
            ["material"] = Material("aas_materials/ass_icon_bag.png", "smooth"),
            ["margin"] = 0.01,
            ["bone"] = "ValveBiped.Bip01_Spine",
        },
    },
    --[[ Don't touch to this part please !! ]]
    ["adminMenu"] = {
        [1] = {
            ["uniqueName"] = "Settings",
            ["material"] = Material("aas_materials/aas_settings.png", "smooth"),
            ["sizeX"] = 0.015, 
            ["sizeY"] = 0.027,
            ["callBack"] = function() end,
        },
        [2] = {
            ["uniqueName"] = "Add",
            ["material"] = Material("aas_materials/aas_plus.png", "smooth"),
            ["sizeX"] = 0.015, 
            ["sizeY"] = 0.026,
            ["callBack"] = function()
                AAS.PositionSettings()
            end,
        }, 
    },
    --[[ Don't touch to this part please !! ]]
    ["positionMenu"] = {
        [1] = {
            ["uniqueName"] = "Add",
            ["material"] = Material("aas_materials/aas_plus.png", "smooth"),
            ["sizeX"] = 0.015, 
            ["sizeY"] = 0.026,
            ["callBack"] = function()
                AAS.PositionSettings()
            end,
        }, 
    },
}

function AAS.BaseItemTable()
    AAS.BaseItems = {
        ["572310302"] = {
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(1.75, -0.875, -33.75),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -40,
                    ["new"] = true,
                },
                ["uniqueId"] = 1,
                ["model"] = "models/sal/gingerbread.mdl",
                ["pos"] = Vector(1.875, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-75.125, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleGingerBread"),
                ["description"] = AAS.GetSentence("descGingerBread"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -2.5938000679016),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -4.8,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 2,
                ["model"] = "models/modified/hat04.mdl",
                ["pos"] = Vector(3.5, -1.96875, 0.1875),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-47.09400177002, -12.75, 275.18798828125),
                ["price"] = 187500,
                ["name"] = AAS.GetSentence("titleCap"),
                ["description"] = AAS.GetSentence("descCap"),
            },
            {
                ["scale"] = Vector(0.875, 1.0625, 0.875),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 3,
                ["model"] = "models/modified/headphones.mdl",
                ["pos"] = Vector(2.875, 0, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(113.5, -0.34400001168251, 90.25),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleHeadphones"),
                ["description"] = AAS.GetSentence("descHeadphones"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -13.3125),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -31.111111111111,
                    ["skin"] = 1,
                },
                ["uniqueId"] = 4,
                ["model"] = "models/sal/hawk_2.mdl",
                ["pos"] = Vector(0.0625, 0.5, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-83.188003540039, 9.5939998626709, -89.96900177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleHawkMask"),
                ["description"] = AAS.GetSentence("descHawkMask"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, -0.625, -2.0625),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -8,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 5,
                ["model"] = "models/modified/hat06.mdl",
                ["pos"] = Vector(5.125, -0.71875, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-81.75, -7.875, -97.5),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBeret"),
                ["description"] = AAS.GetSentence("descBeret"),
            },
            {
                ["scale"] = Vector(0.96875, 1, 0.96875),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0.1875),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -6.38,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 6,
                ["model"] = "models/sal/halloween/headwrap1.mdl",
                ["pos"] = Vector(1.75, 0.96875, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90.09400177002, 0, -90),
                ["price"] = 1875000,
                ["name"] = AAS.GetSentence("titleBandMask"),
                ["description"] = AAS.GetSentence("descBandMask"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -32.875),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -38.222222222222,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 7,
                ["model"] = "models/sal/penguin.mdl",
                ["pos"] = Vector(1.71875, 0.25, -0.25),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titlePinguin"),
                ["description"] = AAS.GetSentence("descPinguin"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0.875),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -10.666666666667,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 8,
                ["model"] = "models/sal/halloween/headwrap2.mdl",
                ["pos"] = Vector(1.46875, 1.09375, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.84400177002, 0, -90.125),
                ["price"] = 750000,
                ["name"] = AAS.GetSentence("titleMummyMask"),
                ["description"] = AAS.GetSentence("descMummyMask"),
            },
            {
                ["scale"] = Vector(1, 1.0625, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -30.218799591064),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -39.111111111111,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 9,
                ["model"] = "models/modified/bandana.mdl",
                ["pos"] = Vector(0.25, -0.46875, 0),
                ["category"] = "Mouse Mask",
                ["job"] = {},
                ["ang"] = Angle(268.75, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBandana"),
                ["description"] = AAS.GetSentence("descBandana"),
            },
            {
                ["scale"] = Vector(0.96875, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -8.8888888888889,
                    ["skin"] = 22,
                },
                ["uniqueId"] = 10,
                ["model"] = "models/sal/halloween/bag.mdl",
                ["pos"] = Vector(2.21875, 1, -0.125),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-88.875, 0.1879999935627, -89.21900177002),
                ["price"] = 562500,
                ["name"] = AAS.GetSentence("titleBag"),
                ["description"] = AAS.GetSentence("descBag"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(-0.875, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = true,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -1.5777777777778,
                    ["skin"] = 4,
                },
                ["uniqueId"] = 11,
                ["model"] = "models/sal/halloween/monkey.mdl",
                ["pos"] = Vector(0.25, 0.875, 0.09375),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(105.59400177002, 185.59399414062, 93.625),
                ["price"] = 243750,
                ["name"] = AAS.GetSentence("titleMonkeyMask"),
                ["description"] = AAS.GetSentence("descMonkeyMask"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, -0.875, 0.875),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -8.7912087912088,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 12,
                ["model"] = "models/sal/halloween/ninja.mdl",
                ["pos"] = Vector(2.21875, 0.59375, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.625, 0, -90.25),
                ["price"] = 1875000,
                ["name"] = AAS.GetSentence("titleNinjaMask"),
                ["description"] = AAS.GetSentence("descNinjaMask"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(-0.34380000829697, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -7.3260073260073,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 13,
                ["model"] = "models/sal/halloween/zombie.mdl",
                ["pos"] = Vector(1.59375, 0.46875, 0.125),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-87, 0, -89.875),
                ["price"] = 2250000,
                ["name"] = AAS.GetSentence("titleZombieMask"),
                ["description"] = AAS.GetSentence("descZombieMask"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -33.75),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -38.222222222222,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 14,
                ["model"] = "models/modified/mask5.mdl",
                ["pos"] = Vector(0.875, 1, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-80, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titlePleaseStop"),
                ["description"] = AAS.GetSentence("descPleaseStop"),
            },
            {
                ["scale"] = Vector(1.09375, 1.0625, 1.0625),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(-1.4375, 0, -0.9375),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -3.6630036630037,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 15,
                ["model"] = "models/sal/halloween/skull.mdl",
                ["pos"] = Vector(3.03125, 0.34375, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.625, -0.25, -90.46900177002),
                ["price"] = 937500,
                ["name"] = AAS.GetSentence("titleSkullMask"),
                ["description"] = AAS.GetSentence("descSkullMask"),
            },
            {
                ["scale"] = Vector(0.96875, 0.875, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -34.406200408936),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -39.56043956044,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 16,
                ["model"] = "models/modified/hat01_fix.mdl",
                ["pos"] = Vector(3.625, 0, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(113.375, 180.125, -266.34399414062),
                ["price"] = 3843750,
                ["name"] = AAS.GetSentence("titleGentlemanshat"),
                ["description"] = AAS.GetSentence("descGentlemanshat"),
            },
            {
                ["scale"] = Vector(0.875, 1.125, 1.125),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -4.3956043956044,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 17,
                ["model"] = "models/sal/halloween/doctor.mdl",
                ["pos"] = Vector(-0.71875, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-68.53099822998, 0, 271.625),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleMaskDoctor"),
                ["description"] = AAS.GetSentence("descMaskDoctor"),
            },
            {
                ["scale"] = Vector(1, 0.875, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -35.875),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -39.56043956044,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 18,
                ["model"] = "models/modified/hat08.mdl",
                ["pos"] = Vector(4.71875, 0.125, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-89.625, 0, -89.625),
                ["price"] = 468750,
                ["name"] = AAS.GetSentence("titleOrangeHat"),
                ["description"] = AAS.GetSentence("descOrangeHat"),
            },
            {
                ["scale"] = Vector(0.96875, 1, 0.9375),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(-7.3125, -8.0312004089355, -37.343799591064),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Spine",
                    ["iconFov"] = -36.630036630037,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 19,
                ["model"] = "models/modified/backpack_3.mdl",
                ["pos"] = Vector(9.5, -5.125, 0),
                ["category"] = "BackPack",
                ["job"] = {},
                ["ang"] = Angle(89.625, 0, 90.125),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBlackBagPack"),
                ["description"] = AAS.GetSentence("descBlackBagPack"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -32.875),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -39.111111111111,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 20,
                ["model"] = "models/sal/pig.mdl",
                ["pos"] = Vector(1.875, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.75, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titlePigHat"),
                ["description"] = AAS.GetSentence("descPigHat"),
            },
            {
                ["scale"] = Vector(0.96875, 0.96875, 0.96875),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -3.125),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -9.1199999999999,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 21,
                ["model"] = "models/modified/hat07.mdl",
                ["pos"] = Vector(5.21875, -0.84375, -0.09375),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(121.59400177002, 169.59399414062, 89.59400177002),
                ["price"] = 281250,
                ["name"] = AAS.GetSentence("titleCap2"),
                ["description"] = AAS.GetSentence("descCap2"),
            },
            {
                ["scale"] = Vector(0.875, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(-1.3125, 1.5625, -28.4375),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Spine",
                    ["iconFov"] = -33.777777777778,
                    ["skin"] = 2,
                },
                ["uniqueId"] = 22,
                ["model"] = "models/modified/backpack_2.mdl",
                ["pos"] = Vector(9.5625, -2.75, 0),
                ["category"] = "BackPack",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, -185.59399414062, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBigBagpack"),
                ["description"] = AAS.GetSentence("descBigBagpack"),
            },
            {
                ["scale"] = Vector(0.875, 0.9375, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(2.9061999320984, 4.375, -25.625),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Spine",
                    ["iconFov"] = -35.164835164835,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 23,
                ["model"] = "models/modified/backpack_1.mdl",
                ["pos"] = Vector(8.75, -3.625, 0),
                ["category"] = "BackPack",
                ["job"] = {},
                ["ang"] = Angle(-89.625, 179.68800354004, -89.625),
                ["price"] = 360000,
                ["name"] = AAS.GetSentence("titleSchoolBagPack"),
                ["description"] = AAS.GetSentence("descSchoolBagPack"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -31.5),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -38.095238095238,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 24,
                ["model"] = "models/sal/acc/fix/beerhat.mdl",
                ["pos"] = Vector(3.625, 0, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-89.625, 0, -89.625),
                ["price"] = 470250,
                ["name"] = AAS.GetSentence("titleBeerHat"),
                ["description"] = AAS.GetSentence("descBeerHat"),
            },
            {
                ["scale"] = Vector(0.5, 0.5625, 0.59375),
                ["options"] = {
                    ["new"] = true,
                    ["activate"] = true,
                    ["iconPos"] = Vector(2.1875, 0.71880000829697, 13.875),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Spine",
                    ["iconFov"] = -31.501831501832,
                    ["skin"] = 0,
                },
                ["uniqueId"] = 25,
                ["model"] = "models/sal/acc/armor01.mdl",
                ["pos"] = Vector(-42.46875, -4.375, 2.1875),
                ["category"] = "BackPack",
                ["job"] = {},
                ["ang"] = Angle(89.65599822998, 0, 92.28099822998),
                ["price"] = 1968750,
                ["name"] = AAS.GetSentence("titleArmor"),
                ["description"] = AAS.GetSentence("descArmor"),
            },
        },
        ["148215278"] = {
            {
                ["scale"] = Vector(0.625, 0.6875, 0.75),
                ["options"] = {
                    ["skin"] = "1",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 26,
                ["model"] = "models/captainbigbutt/skeyler/accessories/duck_tube.mdl",
                ["pos"] = Vector(7.09375, 0.875, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleMaskDuck"),
                ["description"] = AAS.GetSentence("descMaskDuck"),
            },
            {
                ["scale"] = Vector(0.875, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 27,
                ["model"] = "models/captainbigbutt/skeyler/accessories/glasses01.mdl",
                ["pos"] = Vector(3.25, 1.84375, 0),
                ["category"] = "Glasses",
                ["job"] = {},
                ["ang"] = Angle(-70.375, 0, -90),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleGlasses"),
                ["description"] = AAS.GetSentence("descGlasses"),
            },
            {
                ["scale"] = Vector(0.875, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 28,
                ["model"] = "models/captainbigbutt/skeyler/accessories/glasses02.mdl",
                ["pos"] = Vector(3.25, 2, 0.09375),
                ["category"] = "Glasses",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleGlasses2"),
                ["description"] = AAS.GetSentence("descGlasses2"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "1",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 29,
                ["model"] = "models/captainbigbutt/skeyler/hats/afro.mdl",
                ["pos"] = Vector(3.6875, -0.09375, -0.09375),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -86.375),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleAfro"),
                ["description"] = AAS.GetSentence("descAfro"),
            },
            {
                ["scale"] = Vector(0.8125, 0.84375, 0.84375),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 30,
                ["model"] = "models/lordvipes/mariohat/mariohat.mdl",
                ["pos"] = Vector(1.46875, 0, 0.1875),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleMarioHat"),
                ["description"] = AAS.GetSentence("descMarioHat"),
            },
            {
                ["scale"] = Vector(0.90625, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 31,
                ["model"] = "models/captainbigbutt/skeyler/accessories/glasses03.mdl",
                ["pos"] = Vector(3.1875, 3.09375, 0.0625),
                ["category"] = "Glasses",
                ["job"] = {},
                ["ang"] = Angle(-58.875, 0, -89.625),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleGlasses3"),
                ["description"] = AAS.GetSentence("descGlasses3"),
            },
            {
                ["scale"] = Vector(0.75, 0.84375, 0.9375),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 1.75),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 32,
                ["model"] = "models/lordvipes/luigihat/luigihat.mdl",
                ["pos"] = Vector(0, 0, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleLuigiHat"),
                ["description"] = AAS.GetSentence("descLuigiHat"),
            },
            {
                ["scale"] = Vector(0.90625, 0.75, 0.59375),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 33,
                ["model"] = "models/captainbigbutt/skeyler/accessories/glasses04.mdl",
                ["pos"] = Vector(2.90625, 3.65625, 0),
                ["category"] = "Glasses",
                ["job"] = {},
                ["ang"] = Angle(-71.188003540039, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleGlasses4"),
                ["description"] = AAS.GetSentence("descGlasses4"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 34,
                ["model"] = "models/captainbigbutt/skeyler/accessories/monocle.mdl",
                ["pos"] = Vector(2.1875, 4.15625, 0),
                ["category"] = "Glasses",
                ["job"] = {},
                ["ang"] = Angle(-50.09400177002, 0, 0),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleGlasses5"),
                ["description"] = AAS.GetSentence("descGlasses5"),
            },
            {
                ["scale"] = Vector(0.34375, 0.375, 0.375),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 35,
                ["model"] = "models/lordvipes/toadhat/toadhat.mdl",
                ["pos"] = Vector(1, 0.09375, 1.09375),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(9.5939998626709, -112.28099822998, 0),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleToadHat"),
                ["description"] = AAS.GetSentence("descToadHat"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 36,
                ["model"] = "models/lordvipes/servbothead/servbothead.mdl",
                ["pos"] = Vector(5.21875, 0, 0.25),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleServboHead"),
                ["description"] = AAS.GetSentence("descServboHead"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 37,
                ["model"] = "models/captainbigbutt/skeyler/hats/bear_hat.mdl",
                ["pos"] = Vector(5.125, -0.71875, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-71.188003540039, 0.061999998986721, -92.28099822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleCatHat"),
                ["description"] = AAS.GetSentence("descCatHat"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -1.75),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -6.2222222222222,
                    ["new"] = true,
                },
                ["uniqueId"] = 38,
                ["model"] = "models/captainbigbutt/skeyler/hats/strawhat.mdl",
                ["pos"] = Vector(6.09375, 0.25, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(8.625, -89.625, 0),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleStrawHat"),
                ["description"] = AAS.GetSentence("descStrawHat"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 39,
                ["model"] = "models/captainbigbutt/skeyler/hats/bunny_ears.mdl",
                ["pos"] = Vector(5.84375, 0, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-81.75, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleRabbitEar"),
                ["description"] = AAS.GetSentence("descRabbitEar"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0.875),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -5.3333333333333,
                    ["new"] = true,
                },
                ["uniqueId"] = 40,
                ["model"] = "models/captainbigbutt/skeyler/hats/sunhat.mdl",
                ["pos"] = Vector(5.3125, 0.875, 2.625),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(0, -108.75, -19.187999725342),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleSunHat"),
                ["description"] = AAS.GetSentence("descSunHat"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 41,
                ["model"] = "models/gmod_tower/3dglasses.mdl",
                ["pos"] = Vector(3.84375, 2.03125, 0.03125),
                ["category"] = "Glasses",
                ["job"] = {},
                ["ang"] = Angle(-83.188003540039, 0, -89.59400177002),
                ["price"] = 187500,
                ["name"] = AAS.GetSentence("title3DGlasses"),
                ["description"] = AAS.GetSentence("desc3DGlasses"),
            },
            {
                ["scale"] = Vector(0.625, 1, 0.78125),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 42,
                ["model"] = "models/captainbigbutt/skeyler/hats/cat_ears.mdl",
                ["pos"] = Vector(0, 1.96875, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-79.09400177002, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleCatsEars"),
                ["description"] = AAS.GetSentence("descCatsEars"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 43,
                ["model"] = "models/captainbigbutt/skeyler/hats/cat_hat.mdl",
                ["pos"] = Vector(4.375, 0, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-71.188003540039, 0, -92.25),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleCatHat2"),
                ["description"] = AAS.GetSentence("descCatHat2"),
            },
            {
                ["scale"] = Vector(1.09375, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 44,
                ["model"] = "models/gmod_tower/halloween_jasonmask.mdl",
                ["pos"] = Vector(-2.375, -0.9375, 0.09375),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-94.375, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleJasonMask"),
                ["description"] = AAS.GetSentence("descJasonMask"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0.8125, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 45,
                ["model"] = "models/captainbigbutt/skeyler/accessories/mustache.mdl",
                ["pos"] = Vector(1.5, 5.0625, 0),
                ["category"] = "Mouse Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -86.375),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleMustache"),
                ["description"] = AAS.GetSentence("descMustache"),
            },
            {
                ["scale"] = Vector(0.71875, 0.75, 0.5),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 46,
                ["model"] = "models/captainbigbutt/skeyler/hats/cowboyhat.mdl",
                ["pos"] = Vector(5.78125, 0, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-63.28099822998, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleCowboyHat"),
                ["description"] = AAS.GetSentence("descCowboyHat"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 3.5311999320984, 1.75),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -11.555555555556,
                    ["new"] = true,
                },
                ["uniqueId"] = 47,
                ["model"] = "models/captainbigbutt/skeyler/hats/deadmau5.mdl",
                ["pos"] = Vector(2.875, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.625, 0, -89.625),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleDeadmau5"),
                ["description"] = AAS.GetSentence("descDeadmau5"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 48,
                ["model"] = "models/captainbigbutt/skeyler/hats/frog_hat.mdl",
                ["pos"] = Vector(5.125, -0.71875, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-71.188003540039, 0, -92.28099822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleFrogHat"),
                ["description"] = AAS.GetSentence("descFrogHat"),
            },
            {
                ["scale"] = Vector(0.84375, 0.84375, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 50,
                ["model"] = "models/captainbigbutt/skeyler/hats/heartband.mdl",
                ["pos"] = Vector(2.90625, 0.0625, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-76.5, 0, -92.28099822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleHeartBand"),
                ["description"] = AAS.GetSentence("descHeartBand"),
            },
            {
                ["scale"] = Vector(0.9375, 1.1875, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -5.3125),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -22.222222222222,
                    ["new"] = true,
                },
                ["uniqueId"] = 51,
                ["model"] = "models/captainbigbutt/skeyler/hats/pumpkin.mdl",
                ["pos"] = Vector(-0.09375, 0.46875, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-81.75, 0, -92.25),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titlePumpkinHead"),
                ["description"] = AAS.GetSentence("descPumpkinHead"),
            },
            {
                ["scale"] = Vector(0.875, 0.84375, 0.5625),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, -4.4375, -5.3125),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -20.444444444444,
                    ["new"] = true,
                },
                ["uniqueId"] = 52,
                ["model"] = "models/captainbigbutt/skeyler/hats/santa.mdl",
                ["pos"] = Vector(3.625, 0.125, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-60.625, 0, -92.25),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleChristmasHat"),
                ["description"] = AAS.GetSentence("descChristmasHat"),
            },
            {
                ["scale"] = Vector(0.875, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 53,
                ["model"] = "models/captainbigbutt/skeyler/hats/starband.mdl",
                ["pos"] = Vector(2.90625, 0, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-76.46900177002, 0, -92.28099822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleStarHeadband"),
                ["description"] = AAS.GetSentence("descStarHeadband"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 54,
                ["model"] = "models/lordvipes/daftpunk/thomas.mdl",
                ["pos"] = Vector(3.25, 1.1875, -0.125),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-89.5, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleThomasHat"),
                ["description"] = AAS.GetSentence("descThomasHat"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -7.1111111111111,
                    ["new"] = true,
                },
                ["uniqueId"] = 55,
                ["model"] = "models/gmod_tower/sombrero.mdl",
                ["pos"] = Vector(4.4375, 0, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-57.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleSombrero"),
                ["description"] = AAS.GetSentence("descSombrero"),
            },
            {
                ["scale"] = Vector(0.78125, 0.875, 0.875),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 56,
                ["model"] = "models/gmod_tower/headphones.mdl",
                ["pos"] = Vector(3.9375, -0.09375, -0.0625),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-60.78099822998, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleHeadphones2"),
                ["description"] = AAS.GetSentence("descHeadphones2"),
            },
            {
                ["scale"] = Vector(1.09375, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 57,
                ["model"] = "models/gmod_tower/snowboardgoggles.mdl",
                ["pos"] = Vector(4.125, -0.625, -0.09375),
                ["category"] = "Glasses",
                ["job"] = {},
                ["ang"] = Angle(-84.625, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleSnowGoggles"),
                ["description"] = AAS.GetSentence("descSnowGoggles"),
            },
            {
                ["scale"] = Vector(0.6875, 0.65625, 0.59375),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 58,
                ["model"] = "models/captainbigbutt/skeyler/hats/zhat.mdl",
                ["pos"] = Vector(4.75, -0.8125, -0.09375),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-71.15599822998, 23.718999862671, -73.84400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleCap3"),
                ["description"] = AAS.GetSentence("descCap3"),
            },
            {
                ["scale"] = Vector(0.6875, 0.75, 0.84375),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 59,
                ["model"] = "models/captainbigbutt/skeyler/hats/fedora.mdl",
                ["pos"] = Vector(5.125, -0.71875, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-60.65599822998, 0, -92.28099822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleHat"),
                ["description"] = AAS.GetSentence("descHat"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 61,
                ["model"] = "models/gmod_tower/aviators.mdl",
                ["pos"] = Vector(3.09375, 2.5, 0),
                ["category"] = "Glasses",
                ["job"] = {},
                ["ang"] = Angle(-79.09400177002, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleGlasses6"),
                ["description"] = AAS.GetSentence("descGlasses6"),
            },
            {
                ["scale"] = Vector(1, 1.03125, 0.875),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -7.1111111111111,
                    ["new"] = true,
                },
                ["uniqueId"] = 62,
                ["model"] = "models/gmod_tower/baseballcap.mdl",
                ["pos"] = Vector(5.84375, -0.9375, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(121.25, 171.375, 89.625),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleCap4"),
                ["description"] = AAS.GetSentence("descCap4"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 2.6561999320984),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -4.4444444444444,
                    ["new"] = true,
                },
                ["uniqueId"] = 63,
                ["model"] = "models/gmod_tower/drinkcap.mdl",
                ["pos"] = Vector(5.21875, 0.375, -0.3125),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleDrinkCap"),
                ["description"] = AAS.GetSentence("descDrinkCap"),
            },
            {
                ["scale"] = Vector(0.875, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 64,
                ["model"] = "models/gmod_tower/starglasses.mdl",
                ["pos"] = Vector(3.65625, 2.25, 0),
                ["category"] = "Glasses",
                ["job"] = {},
                ["ang"] = Angle(-86.375, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleStarGlasses"),
                ["description"] = AAS.GetSentence("descStarGlasses"),
            },
            {
                ["scale"] = Vector(0.40625, 1.03125, 0.90625),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 65,
                ["model"] = "models/gmod_tower/catears.mdl",
                ["pos"] = Vector(4.5625, -0.59375, -0.15625),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-79.09400177002, -0.34400001168251, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleCatEars"),
                ["description"] = AAS.GetSentence("descCatEars"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(255, 255, 255, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 66,
                ["model"] = "models/gmod_tower/fedorahat.mdl",
                ["pos"] = Vector(6.5625, 0, 0),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-81.75, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleHat2"),
                ["description"] = AAS.GetSentence("descHat2"),
            },
        },
        ["282958377"] = {
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -16,
                    ["new"] = true,
                },
                ["uniqueId"] = 65,
                ["model"] = "models/snowzgmod/payday2/masks/maskbabyrhino.mdl",
                ["pos"] = Vector(3.09375, 3.625, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBabyRhino"),
                ["description"] = AAS.GetSentence("descBabyRhino"),
            },
            {
                ["scale"] = Vector(0.875, 0.96875, 0.875),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -13.333333333333,
                    ["new"] = true,
                },
                ["uniqueId"] = 66,
                ["model"] = "models/snowzgmod/payday2/masks/maskarnold.mdl",
                ["pos"] = Vector(3, 3.625, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-111.75, 0, 269),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleArnoldMask"),
                ["description"] = AAS.GetSentence("descArnoldMask"),
            },
            {
                ["scale"] = Vector(0.9375, 0.9375, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -18.666666666667,
                    ["new"] = true,
                },
                ["uniqueId"] = 67,
                ["model"] = "models/snowzgmod/payday2/masks/maskchuck.mdl",
                ["pos"] = Vector(2.59375, 3.4375, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.625, 0, -88.625),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleChuckMask"),
                ["description"] = AAS.GetSentence("descChuckMask"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(-1.375, 1.125, -0.375),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -13.333333333333,
                    ["new"] = true,
                },
                ["uniqueId"] = 68,
                ["model"] = "models/snowzgmod/payday2/masks/maskdolph.mdl",
                ["pos"] = Vector(3.8125, 3.875, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.75, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleDeerMask"),
                ["description"] = AAS.GetSentence("descDeerMask"),
            },
            {
                ["scale"] = Vector(0.96875, 0.84375, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -16,
                    ["new"] = true,
                },
                ["uniqueId"] = 69,
                ["model"] = "models/snowzgmod/payday2/masks/maskjeanclaude.mdl",
                ["pos"] = Vector(3.3125, 3.625, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-79.09400177002, 0, -89.625),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titlePandaMask"),
                ["description"] = AAS.GetSentence("descPandaMask"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -16.368888888889,
                    ["new"] = true,
                },
                ["uniqueId"] = 70,
                ["model"] = "models/snowzgmod/payday2/masks/maskmonkeybusiness.mdl",
                ["pos"] = Vector(3.125, 3.09375, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 187500,
                ["name"] = AAS.GetSentence("titleMonkeyMask2"),
                ["description"] = AAS.GetSentence("descMonkeyMask2"),
            },
            {
                ["scale"] = Vector(0.9375, 0.9375, 0.84375),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -14.222222222222,
                    ["new"] = true,
                },
                ["uniqueId"] = 71,
                ["model"] = "models/snowzgmod/payday2/masks/maskmark.mdl",
                ["pos"] = Vector(2.9375, 3.8125, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.125, 2.7809998989105, -89.625),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBearMask"),
                ["description"] = AAS.GetSentence("descBearMask"),
            },
            {
                ["scale"] = Vector(0.9375, 0.96875, 0.875),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -15.06,
                    ["new"] = true,
                },
                ["uniqueId"] = 72,
                ["model"] = "models/snowzgmod/payday2/masks/maskthehog.mdl",
                ["pos"] = Vector(2.875, 4.125, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.625, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titlePigMask"),
                ["description"] = AAS.GetSentence("descPigMask"),
            },
        },
        ["158532239"] = {
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "1",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -6.2188000679016),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -24.888888888889,
                    ["new"] = true,
                },
                ["uniqueId"] = 73,
                ["model"] = "models/fallout 3/polish_beret.mdl",
                ["pos"] = Vector(6.46875, 0.9375, 1.4375),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titlePolishBeret"),
                ["description"] = AAS.GetSentence("descPolishBeret"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "2",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -6.2188000679016),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -24.888888888889,
                    ["new"] = true,
                },
                ["uniqueId"] = 73,
                ["model"] = "models/fallout 3/polish_beret.mdl",
                ["pos"] = Vector(6.46875, 0.9375, 1.4375),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titlePolishBeret2"),
                ["description"] = AAS.GetSentence("descPolishBeret2"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "3",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, -6.2188000679016),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -24.888888888889,
                    ["new"] = true,
                },
                ["uniqueId"] = 73,
                ["model"] = "models/fallout 3/polish_beret.mdl",
                ["pos"] = Vector(6.46875, 0.9375, 1.4375),
                ["category"] = "Hat",
                ["job"] = {},
                ["ang"] = Angle(-89.59400177002, 0, -89.59400177002),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titlePolishBeret3"),
                ["description"] = AAS.GetSentence("descPolishBeret3"),
            },
        },
        ["551144079"] = {
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet"),
                ["description"] = AAS.GetSentence("descBikeHelmet"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "1",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet2"),
                ["description"] = AAS.GetSentence("descBikeHelmet2"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "2",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet3"),
                ["description"] = AAS.GetSentence("descBikeHelmet3"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "3",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet4"),
                ["description"] = AAS.GetSentence("descBikeHelmet4"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "4",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet5"),
                ["description"] = AAS.GetSentence("descBikeHelmet5"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "5",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet6"),
                ["description"] = AAS.GetSentence("descBikeHelmet6"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "6",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet7"),
                ["description"] = AAS.GetSentence("descBikeHelmet7"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "7",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet8"),
                ["description"] = AAS.GetSentence("descBikeHelmet8"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "8",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet9"),
                ["description"] = AAS.GetSentence("descBikeHelmet9"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "9",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet10"),
                ["description"] = AAS.GetSentence("descBikeHelmet10"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "10",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet11"),
                ["description"] = AAS.GetSentence("descBikeHelmet11"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "11",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet12"),
                ["description"] = AAS.GetSentence("descBikeHelmet12"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "12",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet13"),
                ["description"] = AAS.GetSentence("descBikeHelmet13"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "13",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet14"),
                ["description"] = AAS.GetSentence("descBikeHelmet14"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "14",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = 0,
                    ["new"] = true,
                },
                ["uniqueId"] = 74,
                ["model"] = "models/dean/gtaiv/helmet.mdl",
                ["pos"] = Vector(3.09375, 0, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-90, 0, -89.65599822998),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleBikeHelmet15"),
                ["description"] = AAS.GetSentence("descBikeHelmet15"),
            },
        },
        ["826536617"] = {
            {
                ["scale"] = Vector(0.46875, 0.46875, 0.5),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -8,
                    ["new"] = true,
                },
                ["uniqueId"] = 107,
                ["model"] = "models/props/pumpkin_z.mdl",
                ["pos"] = Vector(3.625, 0.9375, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(-89.625, 0, -89.625),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titlePumpkinMask"),
                ["description"] = AAS.GetSentence("descPumpkinMask"),
            },
        },
        ["166177187"] = {
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 2.6561999320984, -0.875),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -13.333333333333,
                    ["new"] = true,
                },
                ["uniqueId"] = 108,
                ["model"] = "models/horsie/horsiemask.mdl",
                ["pos"] = Vector(3.46875, 3.5, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(0, -89.625, -21.093999862671),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleHorseMask"),
                ["description"] = AAS.GetSentence("descHorseMask"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "1",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 2.6561999320984, -0.875),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -13.333333333333,
                    ["new"] = true,
                },
                ["uniqueId"] = 108,
                ["model"] = "models/horsie/horsiemask.mdl",
                ["pos"] = Vector(3.46875, 3.5, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(0, -89.625, -21.093999862671),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleHorseMask2"),
                ["description"] = AAS.GetSentence("descHorseMask2"),
            },
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "2",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 2.6561999320984, -0.875),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -13.333333333333,
                    ["new"] = true,
                },
                ["uniqueId"] = 108,
                ["model"] = "models/horsie/horsiemask.mdl",
                ["pos"] = Vector(3.46875, 3.5, 0),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(0, -89.625, -21.093999862671),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleHorseMask3"),
                ["description"] = AAS.GetSentence("descHorseMask3"),
            },
        },
        ["354739227"] = {
            {
                ["scale"] = Vector(1, 1, 1),
                ["options"] = {
                    ["skin"] = "0",
                    ["activate"] = true,
                    ["iconPos"] = Vector(0, 0, 0),
                    ["color"] = Color(240, 240, 240, 255),
                    ["vip"] = false,
                    ["bone"] = "ValveBiped.Bip01_Head1",
                    ["iconFov"] = -26.666666666667,
                    ["new"] = true,
                },
                ["uniqueId"] = 109,
                ["model"] = "models/russianhat1.mdl",
                ["pos"] = Vector(-5.625, -0.71875, 0.1875),
                ["category"] = "Face Mask",
                ["job"] = {},
                ["ang"] = Angle(84.34400177002, 0.93800002336502, 89.25),
                ["price"] = 375000,
                ["name"] = AAS.GetSentence("titleRussianHat"),
                ["description"] = AAS.GetSentence("descRussianHat"),
            },
        }
    }
end
AAS.BaseItemTable()