ENT.Type                    = "ai"
ENT.Base                    = "base_ai"
ENT.AutomaticFrameAdvance   = true
ENT.PrintName               = "Export Manager"
ENT.Author                  = "ZeroChain"
ENT.Category                = "Zeros GrowOP 2"
ENT.Spawnable               = true
ENT.AdminSpawnable          = false
ENT.RenderGroup             = RENDERGROUP_BOTH
ENT.Model 					= "models/odessa.mdl"
