--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

SWEP.PrintName = "Inventario"
SWEP.Instructions = "Click principal: Recoger artículo\nClick secundario: Abrir inventario"
SWEP.Base = "weapon_base"
SWEP.Author = "sleeppyy"
SWEP.Category = "Xenin"

SWEP.WorldModel = ""
SWEP.ViewModel = "models/weapons/c_arms.mdl"

SWEP.UseHands = false
SWEP.Spawnable = false

SWEP.ViewModelFOV = 50
SWEP.ViewModelFlip = false

SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 0
SWEP.Primary.Automatic = false
SWEP.Primary.Ammo = "none"

SWEP.Secondary.ClipSize = -1
SWEP.Secondary.DefaultClip = 0
SWEP.Secondary.Automatic = false
SWEP.Secondary.Ammo = "none"

SWEP.Slot = 1

function SWEP:Initialize()
  self:SetHoldType("normal")
end

function SWEP:PrimaryAttack()
  if CLIENT then return end

  if SERVER then
    self.Owner:XeninInventory():Pickup(self.Owner:GetEyeTrace().Entity)
  end
end

function SWEP:SecondaryAttack()
  if SERVER then return end

  self.Owner:ConCommand("inventory")
end
