--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local PANEL = {}

function PANEL:Init()
  self.Bank = self:Add("XeninInventory.Bank.Internal")

  self.XeninInventory = self:Add("XeninUI.Frame")
  self.XeninInventory.closeBtn:SetVisible(false)
  self.XeninInventory:SetTitle(XeninInventory:GetPhrase("XeninInventory.Title"))
  self.XeninInventory.Paint = function(pnl, w, h)
    draw.RoundedBox(6, 0, 0, w, h, XeninUI.Theme.Background)
  end

  self.XeninInventory.Panel = self.XeninInventory:Add("XeninInventory.Slots")
  self.XeninInventory.Panel:SetColumns(XeninInventory.Config.BankItemsPerRow)
  self.XeninInventory.Panel:Dock(FILL)
  self.XeninInventory.Panel:DockMargin(8, 8, 8, 8)
  self.XeninInventory.Panel:CreateFields(LocalPlayer():XeninInventory():GetInventory(), true)
end

function PANEL:PerformLayout(w, h)
  local size = w / 2 - 64 / 2

  self.Bank:SetSize(size, h)
  self.XeninInventory:SetSize(size, h)
  self.XeninInventory:SetPos(w - self.XeninInventory:GetWide(), 0)
end

vgui.Register("XeninInventory.Bank", PANEL)

XeninUI:CreateFont("XeninInventory.Bank.Upgrade", 18)

local PANEL = {}

function PANEL:Init()
  self:SetTitle(XeninInventory:GetPhrase("Bank.Title"))

  self.XeninInventory = self:Add("XeninInventory.Slots")
  self.XeninInventory:SetColumns(XeninInventory.Config.BankItemsPerRow)
  self.XeninInventory:Dock(FILL)
  self.XeninInventory:DockMargin(8, 8, 8, 8)

  self:Refresh()
end

function PANEL:Refresh()
  local inv = LocalPlayer():XeninInventory()
  local tbl = inv:GetBank()

  self.XeninInventory:CreateFields(tbl, true, inv:GetBankSlots(), true)
end

function PANEL:CreateFields()
  local tbl = {}

  self.XeninInventory:CreateFields(tbl, true)
end

vgui.Register("XeninInventory.Bank.Internal", PANEL, "XeninUI.Frame")

local PANEL = {}

function PANEL:Init()
  self.Panel = self:Add("XeninInventory.Bank")
  self.Panel.Bank.closeBtn.DoClick = function(pnl)
    self:Remove()
  end

  self.Blur = 0
  self:Lerp("Blur", 4, 0.15)

  XeninInventory.Bank = self
end

function PANEL:PerformLayout(w, h)
  local width = math.min(ScrW(), 1400)
  local height = math.min(ScrH(), 828)

  self.Panel:SetSize(width, height)
  self.Panel:SetPos(w / 2 - width / 2, h / 2 - height / 2)
end

function PANEL:OnRemove()
  XeninInventory.Bank = nil
end

function PANEL:Paint(w, h)
  XeninUI:DrawBlur(self, self.Blur)
end

vgui.Register("XeninInventory.Bank.Frame", PANEL, "EditablePanel")
