--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local PANEL = {}

function PANEL:Init()
  XeninInventory.Frame = self

  self.body = self:Add("XeninInventory.XeninInventory")
  self.body:Dock(FILL)





end

function PANEL:OnRemove()
  XeninInventory.Frame = nil
end

function PANEL:PerformLayout(w, h)
  self.BaseClass.PerformLayout(self, w, h)


end
vgui.Register("XeninInventory.Frame", PANEL, "XeninUI.Frame")

concommand.Add("inventory", function()
  if IsValid(XeninInventory.Frame) then return end
  if (!XeninInventory:CanUseInventory(LocalPlayer())) then
    return LocalPlayer():XeninInventory():Message(XeninInventory:GetPhrase("ChatCommand.AccessRestricted"))
  end

  local frame = vgui.Create("XeninInventory.Frame")
  local width = math.min(ScrW(), 1100)
  local height = math.min(ScrH(), 828)
  frame:SetSize(width, height)
  frame:Center()
  frame:MakePopup()
  frame:SetTitle("Inventory")
end)
