--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local PANEL = {}

XeninUI:CreateFont("XeninInventory.Field.Name", 15)
XeninUI:CreateFont("XeninInventory.Field.Name.Small", 12)
XeninUI:CreateFont("XeninInventory.Field.Name.Smallest", 9)
XeninUI:CreateFont("XeninInventory.Field.Amount", 15)

AccessorFunc(PANEL, "m_backgroundColor", "BackgroundColor")
AccessorFunc(PANEL, "m_nameColor", "NameColor")
AccessorFunc(PANEL, "m_nameTextColor", "NameTextColor")
AccessorFunc(PANEL, "m_name", "Name")
AccessorFunc(PANEL, "m_amount", "Amount")
AccessorFunc(PANEL, "m_id", "ID")
AccessorFunc(PANEL, "m_isBank", "IsBank")
AccessorFunc(PANEL, "m_isAdmin", "IsAdmin")

PANEL.Popup = {
  [XeninInventory:GetPhrase("XeninInventory.Popup.Equip")] = function(self, id, btn)
    local ply = LocalPlayer()
    local inv = ply:XeninInventory()
    local slot = inv:Get(id)
    if (!slot) then return end
    local item = XeninInventory:GetItem(slot.dropEnt)
    if (!item) then return end
    if (!item.Actions.Equip) then return end
    local canEquip, reason = item.Actions.Equip.Pre(item, ply, slot, self)

    if (!canEquip) then
      XeninUI:Notify(reason, NOTIFY_ERROR, 4, XeninUI.Theme.Red)
      chat:AddText(XeninUI.Theme.Red, XeninInventory.Config.PrefixText .. " ", color_white, reason)

      return
    end

    if inv:ReduceAmount(id, 1, nil, item.UseDataAmount) then
      item.Actions.Equip:Action(ply, slot.ent, slot, self)

      self:SetItem(inv:Get(id))

      net.Start("XeninInventory.Equip")
      net.WriteUInt(id, 10)
      net.SendToServer()
    end
  end,
  [XeninInventory:GetPhrase("XeninInventory.Popup.Drop")] = function(self, id, btn)
    local ply = LocalPlayer()
    local inv = ply:XeninInventory()
    local slot = inv:Get(id)
    if (!slot) then return end
    local item = XeninInventory:GetItem(slot.dropEnt)
    if (!item) then return end
    if (!item.Actions.Drop) then return end

    if inv:ReduceAmount(id, 1) then
      local str = XeninInventory:GetPhrase("ConCommand.Drop", {
      item = item.GetDisplayName and item:GetDisplayName(slot) or item:GetName(slot) })
      XeninUI:Notify(str, NOTIFY_GENERIC, 4, XeninUI.Theme.Green)
      chat:AddText(XeninInventory.Config.PrefixCol, XeninInventory.Config.PrefixText .. " ", color_white, str)

      self:SetItem(inv:Get(id))

      net.Start("XeninInventory.Drop")
      net.WriteUInt(id, 10)
      net.SendToServer()
    end
  end,
  [XeninInventory:GetPhrase("XeninInventory.Popup.Drop All")] = function(self, id, btn)
    local ply = LocalPlayer()
    local inv = ply:XeninInventory()
    local slot = inv:Get(id)
    if (!slot) then return end
    local item = XeninInventory:GetItem(slot.dropEnt)
    if (!item) then return end
    local amount = slot.amount

    if inv:ReduceAmount(id, amount) then
      local str = XeninInventory:GetPhrase("ConCommand.DropAll", {
        amount = amount,
        item = item.GetDisplayName and item:GetDisplayName(slot) or item:GetName(slot)
      })
      XeninUI:Notify(str, NOTIFY_GENERIC, 4, XeninUI.Theme.Green)
      chat:AddText(XeninInventory.Config.PrefixCol, XeninInventory.Config.PrefixText .. " ", color_white, str)

      self:SetItem(inv:Get(id))

      net.Start("XeninInventory.DropAll")
      net.WriteUInt(id, 10)
      net.SendToServer()
    end
  end,
  [XeninInventory:GetPhrase("XeninInventory.Popup.Destroy")] = function(self, id, btn)
    local ply = LocalPlayer()
    local inv = ply:XeninInventory()
    local slot = inv:Get(id)
    if (!slot) then return end
    local item = XeninInventory:GetItem(slot.dropEnt)
    if (!item) then return end
    local amount = slot.amount

    local popup = vgui.Create("XeninUI.Query")
    popup:SetSize(ScrW(), ScrH())
    popup:SetBackgroundWidth(400)
    popup:SetBackgroundHeight(140)
    popup:SetTitle(XeninInventory:GetPhrase("ConCommand.Destroy.Popup.Title", {
    item = item:GetName(slot) }))
    popup:SetText(XeninInventory:GetPhrase("ConCommand.Destroy.Popup.Desc", {
    item = item:GetName(slot) }))
    popup:SetAccept(XeninInventory:GetPhrase("ConCommand.Destroy.Popup.Yes"), function()
      inv:Set(id, nil)
      if IsValid(self) then
        self:SetItem(inv:Get(id))
      end

      local str = XeninInventory:GetPhrase("ConCommand.Destroy", {
        amount = amount,
        item = item:GetName(slot)
      })
      XeninUI:Notify(str, NOTIFY_ERROR, 4, XeninUI.Theme.Green)
      chat:AddText(XeninInventory.Config.PrefixCol, XeninInventory.Config.PrefixText .. " ", color_white, str)

      net.Start("XeninInventory.Destroy")
      net.WriteUInt(id, 10)
      net.SendToServer()
    end)
    popup:SetDecline(XeninInventory:GetPhrase("ConCommand.Destroy.Popup.No"), function() end)
    popup:MakePopup()
  end,
  [XeninInventory:GetPhrase("XeninInventory.Popup.Use")] = function(self, id, btn)
    local ply = LocalPlayer()
    local inv = ply:XeninInventory()
    local slot = inv:Get(id)
    if (!slot) then return end
    local item = XeninInventory:GetItem(slot.dropEnt)
    if (!item) then return end

    local canEquip, reason = item.Actions.Use.Pre(item, ply, slot, self)
    if (!canEquip) then
      XeninUI:Notify(reason, NOTIFY_ERROR, 4, XeninUI.Theme.Red)
      chat:AddText(XeninUI.Theme.Red, XeninInventory.Config.PrefixText .. " ", color_white, reason)

      return
    end

    if inv:ReduceAmount(id, 1) then
      item.Actions.Use:Action(item, ply, slot.ent, slot, self)
    end

    net.Start("XeninInventory.Use")
    net.WriteUInt(id, 10)
    net.SendToServer()

    self:SetItem(inv:Get(id))
  end,
  [XeninInventory:GetPhrase("XeninInventory.Popup.Drop Amount")] = function(self, id, btn)
    local ply = LocalPlayer()
    local inv = ply:XeninInventory()
    local slot = inv:Get(id)
    if (!slot) then return end
    local item = XeninInventory:GetItem(slot.dropEnt)
    if (!item) then return end
    local amount = slot.data.amount or slot.data.Amount or slot.amount

    local function err(msg)
      chat.AddText(XeninInventory.Config.PrefixCol or color_white, XeninInventory.Config.PrefixText .. " ", color_white, msg)
    end

    local popup = vgui.Create("XeninInventory.DropAmount")
    popup:SetSize(ScrW(), ScrH())
    popup:SetTitle(XeninInventory:GetPhrase("XeninInventory.Popup.Drop Amount"))
    popup.textentry.textentry:SetNumeric(true)
    popup.CheckFunction = function(pnl)
      local text = pnl.textentry:GetText()
      text = tonumber(text)
      if (!text) then err(XeninInventory:GetPhrase("XeninInventory.Popup.DropAmount.Error.Invalid"))return end
      if (text <= 0) then err(XeninInventory:GetPhrase("XeninInventory.Popup.DropAmount.Error.TooLow"))return end
      if (text > amount) then err(XeninInventory:GetPhrase("XeninInventory.Popup.DropAmount.Error.TooHigh"))return end

      return true
    end
    popup.PassedFunction = function(pnl)
      local text = pnl.textentry:GetText()
      text = tonumber(text)

      if (amount > slot.amount) then
        local newAmount = (slot.data.amount or slot.data.Amount) - text
        if (newAmount < 0) then return end

        slot.data.amount = slot.data.amount and newAmount
        slot.data.Amount = slot.data.Amount and newAmount

        net.Start("XeninInventory.DropAmount.Data")
        net.WriteUInt(id, 10)
        net.WriteUInt(text, 32)
        net.SendToServer()

        if (newAmount == 0) then
          inv:Set(id, nil)
        end
      else
        if inv:ReduceAmount(id, text) then
          net.Start("XeninInventory.DropAmount")
          net.WriteUInt(id, 10)
          net.WriteUInt(text, 32)
          net.SendToServer()
        end
      end

      pnl:Remove()
    end

    popup:MakePopup()
  end
}

local matGradient = Material("gui/gradient_down", "smooth")

function PANEL:Init()
  self:SetText("")
  self:SetBackgroundColor(XeninInventory.Config.SlotNameColor or XeninUI.Theme.Primary)
  self:SetNameColor(XeninUI.Theme.Primary)
  self:SetNameTextColor(Color(180, 180, 180))
  self:SetName(false)
  self:SetAmount(0)

  self.isInventoryField = true

  self.model = self:Add("DModelPanel")
  self.model:SetMouseInputEnabled(false)
  self.model:SetVisible(false)
  self.model.LayoutEntity = function() end
  local oldPaint = self.model.Paint
  self.model.Paint = function(pnl, w, h)
    oldPaint(pnl, w, h)

    local amount
    if (self.info and self.info.data) then
      amount = self.info.data.ammo or self.info.data.repair or self.info.data.health or self:GetAmount()
    else
      amount = self:GetAmount()
    end

    local visualAmount = self.item:GetVisualAmount(self.info) or 0
    if (amount > 1 or visualAmount > 1) then
      local bgColor = Color(0, 0, 0, 205)
      local max = 100
      if self.cat then
        bgColor = XeninInventory.Config.Categories[self.cat].amountBackgroundColor or bgColor
        max = XeninInventory.Config.Categories[self.cat].maxStack or max
      end

      local str = XeninInventory:GetPhrase("XeninInventory.Field.Amount", {
      amount = (visualAmount and (visualAmount == 0 and amount or visualAmount) or amount) or amount })
      if (self:GetAmount() >= max and max != 1) then
        str = XeninInventory:GetPhrase("XeninInventory.Field.MaxAmount", {
        amount = max })
      end
      surface.SetFont("XeninInventory.Field.Amount")
      local tw, th = surface.GetTextSize(str)
      local x = w - 10 - tw - 2
      local y = 10

      local bgColor = Color(0, 0, 0, 165)
      if self.cat then
        bgColor = XeninInventory.Config.Categories[self.cat].amountBackgroundColor or bgColor
      end

      draw.RoundedBox(6, x, y - 1, tw + 5, th + 1, bgColor)
      draw.SimpleText(str, "XeninInventory.Field.Amount", w - 9, 9, color_white, TEXT_ALIGN_RIGHT, TEXT_ALIGN_TOP)
    end
  end

  self.overlayAlpha = 0

  hook.Add("XeninInventory.SlotUpdateFromServer", self, function(self, id, tbl, bank)
    if (self:GetID() != id) then return end

    if (self:GetIsBank() and bank) then
      self:SetItem(tbl)
    else
      self:SetItem(tbl)
    end
  end)
end

function PANEL:DoRightClick()
  self:DoClick()
end

function PANEL:DoClick()

  if (self:GetIsBank() and !self:GetIsAdmin()) then return end

  if (!self.model:IsVisible()) then return end

  if self:GetIsAdmin() then
    local x, y = gui.MouseX(), gui.MouseY()
    self.popup = XeninUI:DropdownPopup(x, y)
    local panel = self.popup
    panel:AddChoice("Remove Item", function(btn)
      local ply = player.GetBySteamID64(self:GetIsAdmin())
      local id = self:GetID()
      if IsValid(ply) then
        local inv = ply:XeninInventory()
        inv:Set(id, nil, self:GetIsBank())
      end

      self:SetItem(nil)

      net.Start("XeninInventory.Admin.RemoveItem")
      net.WriteString(self:GetIsAdmin())
      net.WriteUInt(id, 16)
      net.WriteBool(self:GetIsBank())
      net.SendToServer()
    end)

    return
  end

  local func = function(btn)
    self.Popup[btn:GetText()](self, self:GetID(), btn)
  end

  local x, y = gui.MouseX(), gui.MouseY()
  self.popup = XeninUI:DropdownPopup(x, y)
  local panel = self.popup

  local item = XeninInventory:GetItem(self.dropEnt)
  local sorted = {}
  for i, v in pairs(item.Actions) do
    table.insert(sorted, {
      name = i,
      sortOrder = v.SortOrder
    })
  end
  table.sort(sorted, function(a, b)
    return a.sortOrder < b.sortOrder
  end)

  for i, v in ipairs(sorted) do
    if (v.name == XeninInventory:GetPhrase("XeninInventory.Popup.DropAll")) then
      self.info = self.info or {}
      self.info.data = self.info.data or {}
      local amount = self.info.data.amount or self.info.data.Amount or self:GetAmount() or 0

      if (amount > 1) then
        panel:AddChoice(XeninInventory:GetPhrase("XeninInventory.Popup." .. v.name), func)
      end

      continue
    end

    panel:AddChoice(XeninInventory:GetPhrase("XeninInventory.Popup." .. v.name), func)
  end
  panel:AddChoice(XeninInventory:GetPhrase("XeninInventory.Popup.Destroy"), func, nil, nil, matDestroy)
end

function PANEL:OnRemove()
  if IsValid(self.popup) then
    self.popup:Remove()
  end

  if IsValid(self.hover) then
    self.hover:Remove()
  end
end

function PANEL:PaintFunction(pnl, w, h)
  local amount
  if (self.info and self.info.data) then
    amount = self.info.data.ammo or self.info.data.repair or self.info.data.health or self:GetAmount()
  else
    amount = self:GetAmount()
  end

  local visualAmount = self.item:GetVisualAmount(self.info) or 0
  if ((amount > 1 or visualAmount > 1) and self.displayAmount) then
    local bgColor = Color(0, 0, 0, 205)
    local max = 100
    if self.cat then
      bgColor = XeninInventory.Config.Categories[self.cat].amountBackgroundColor or bgColor
      max = XeninInventory.Config.Categories[self.cat].maxStack or max
    end

    local displayAmt = (visualAmount and (visualAmount == 0 and amount or visualAmount) or amount) or amount
    local str = XeninInventory:GetPhrase("XeninInventory.Field.Amount", {
    amount = displayAmt })
    if (self:GetAmount() >= max and max != 1) then
      str = XeninInventory:GetPhrase("XeninInventory.Field.MaxAmount", {
      amount = displayAmt })
    end
    surface.SetFont("XeninInventory.Field.Amount")
    local tw, th = surface.GetTextSize(str)
    local x = w - 10 - tw - 2
    local y = 10

    local bgColor = Color(0, 0, 0, 165)
    if self.cat then
      bgColor = XeninInventory.Config.Categories[self.cat].amountBackgroundColor or bgColor
    end

    draw.RoundedBox(6, x, y - 1, tw + 5, th + 1, bgColor)
    draw.SimpleText(str, "XeninInventory.Field.Amount", w - 9, 9, color_white, TEXT_ALIGN_RIGHT, TEXT_ALIGN_TOP)
  end
end

function PANEL:RecreateModelPanel(image)
  self.model:Remove()

  if image then
    self.model = self:Add("DPanel")
    self.model:SetMouseInputEnabled(false)
    self.model:SetVisible(false)
    self.model.SetImage = function(pnl, img)
      pnl.mat = Material(img)
    end
    self.model.margin = 10
    self.model.Paint = function(pnl, w, h)
      local margin = pnl.margin
      surface.SetDrawColor(color_white)
      surface.SetMaterial(pnl.mat)
      surface.DrawTexturedRect(margin, margin, w - (margin * 2), h - (margin * 2))

      self:PaintFunction(pnl, w, h)
    end
  else
    self.model = self:Add("DModelPanel")
    self.model:SetMouseInputEnabled(false)
    self.model:SetVisible(false)
    self.model.LayoutEntity = function() end
    local oldPaint = self.model.Paint
    self.model.Paint = function(pnl, w, h)
      oldPaint(pnl, w, h)

      self:PaintFunction(pnl, w, h)
    end
  end
end

function PANEL:SetItem(tbl)
  tbl = tbl or {}
  local ply = LocalPlayer()
  local rarity = XeninInventory:GetRarity(tbl)
  local cat = XeninInventory.Config.Categories[rarity]

  if (!cat and tbl.model) then
    rarity = 1
    cat = XeninInventory.Config.Categories[rarity]
  end
  self.cat = rarity
  local item = XeninInventory:GetItem(tbl.dropEnt)
  local name = item and item:GetName(tbl)
  local model = item and item:GetModel(tbl)
  local displayAmount = item and !item.DontDisplayAmount
  if (displayAmount == nil) then displayAmount = true end

  self:SetName(tbl.ent and name or false)
  self:SetNameColor(tbl.name and Color(0, 0, 0, 200) or XeninInventory.Config.SlotNameColor or XeninUI.Theme.Primary)
  self:SetNameTextColor(XeninInventory.Config.SlotNameTextColor or Color(225, 225, 225))
  self:SetBackgroundColor(model and cat.color or XeninInventory.Config.SlotColor or XeninUI.Theme.Primary)
  self:SetAmount(tbl.amount or 0)
  self.item = item
  self.ent = tbl.ent
  self.dropEnt = tbl.dropEnt
  self.info = tbl
  self.displayAmount = displayAmount

  if model then
    local isMat = model:find(".png")
    local isMdlPnl = IsValid(self.model) and self.model:GetName() == "DModelPanel"

    if (isMat and isMdlPnl) then
      self:RecreateModelPanel(true)
      self.model:SetImage(model)
      self.model:SetVisible(true)
    elseif (!isMat and isMdlPnl) then
      self:RecreateModelPanel()

      self.model:SetModel(model)
      self.model:SetVisible(true)
      if IsValid(self.model.Entity) then
        local mn, mx = self.model.Entity:GetRenderBounds()
        local size = 0
        size = math.max(size, math.abs(mn.x) + math.abs(mx.x))
        size = math.max(size, math.abs(mn.y) + math.abs(mx.y))
        size = math.max(size, math.abs(mn.z) + math.abs(mx.z))
        local viewModifier = item.GetCameraModifiers and item:GetCameraModifiers(self.info) or {}
        local FOV = viewModifier.FOV
        local x = viewModifier.X or 0
        local y = viewModifier.Y or 0
        local z = viewModifier.Z or 0
        local ang = viewModifier.Angles
        local pos = viewModifier.Pos
        self.model:SetFOV(FOV or item.FOV or 33)
        self.model:SetCamPos(Vector(size + x, size + 30 + y, size - 30 + z))
        self.model:SetLookAt((mn + mx) * 0.5)
        if ang then
          self.model.Entity:SetAngles(ang)
        end
        if pos then
          self.model.Entity:SetPos(pos)
        end
        local skin = item.GetSkin and item:GetSkin(self.info)
        if skin then
          self.model.Entity:SetSkin(skin)
        end
        local color = item.GetColor and item:GetColor(self.info)
        if color then
          self.model.Entity:SetColor(color)
        end
        local bodygroup, value = item.GetBodygroup and item:GetBodygroup(self.info)
        if bodygroup then
          self.model.Entity:SetBodygroup(bodygroup, value)
        end
        local modelControl = item.GetClientsideModel and item:GetClientsideModel(self.info, self.model)

        if (SH_EASYSKINS and XeninInventory.Config.EasySkinsEnabled and tbl.dropEnt == "spawned_weapon") then
          local skinTbl = SH_EASYSKINS.GetEnabledPurchasedSkinByClass(ply, tbl.ent)

          if skinTbl then
            local skin = SH_EASYSKINS.GetSkin(skinTbl.skinID)

            if skin then
              SH_EASYSKINS.ApplySkinToModel(self.model.Entity, skin.material.path)
            end
          end
        end
      end
    end
  else
    self.model:SetVisible(false)
  end

  self:InvalidateLayout()
end

function PANEL:SetItemByID(id, bank)
  local inv = LocalPlayer():XeninInventory()
  local tbl = bank and inv:GetBank() or inv:GetInventory()

  self:SetItem(tbl[id])
  self:SetID(id)
  self:SetDroppable(tbl[id])
end

function PANEL:OnStartDragging()
  self:OnCursorEntered()

  if IsValid(self.hover) then
    self.hover:Remove()
  end
end

function PANEL:OnStopDragging()
  if (!self:IsHovered()) then
    self:OnCursorExited()
  end

  if IsValid(self.hover) then
    self.hover:Remove()
  end
end

function PANEL:SetDroppable(bool, bank)
  self.m_DragSlot = nil

  if (bool and self.model:IsVisible()) then
    self:Droppable("XeninInventory.Field")
  end

  self:Receiver("XeninInventory.Field", function(self, tbl, dropped)
    if (!dropped) then return end
    local droppedPnl = tbl[1]
    if (!droppedPnl) then return end
    if (!XeninInventory:CanUseInventory(LocalPlayer())) then
      return LocalPlayer():XeninInventory():Message(XeninInventory:GetPhrase("ChatCommand.AccessRestricted"))
    end

    local tempIsBank = droppedPnl:GetIsBank()
    local temp2IsBank = self:GetIsBank()
    local temp = droppedPnl:GetID()
    local temp2 = self:GetID()

    local inv = LocalPlayer():XeninInventory()
    if (tempIsBank and temp2IsBank) then
      inv:Swap(temp, temp2, true)

      droppedPnl:SetItemByID(temp, true)
      self:SetItemByID(temp2, true)
    elseif (tempIsBank and !temp2IsBank) then
      inv:SwapBank(temp2, temp)

      droppedPnl:SetItemByID(temp, true)
      self:SetItemByID(temp2)
    elseif (!tempIsBank and temp2IsBank) then
      inv:SwapBank(temp, temp2)

      droppedPnl:SetItemByID(temp)
      self:SetItemByID(temp2, true)
    elseif (!temp2IsBank and !tempIsBank) then
      inv:Swap(temp, temp2)

      droppedPnl:SetItemByID(temp)
      self:SetItemByID(temp2)
    end
  end)
end

function PANEL:PerformLayout(w, h)
  self.model:SetPos(1, 1)
  self.model:SetSize(w - 2, h - 2 - (self:GetName() and 24 or 0))
end

function PANEL:OnCursorEntered()
  self:Lerp("overlayAlpha", 140)
  if (!self.info) then return end

  self:CreateHover()
end

function PANEL:CreateHover()
  local item = XeninInventory:GetItem(self.info.dropEnt)
  if (!item) then return end
  if (!item.Hover) then return end

  local x, y = self:LocalToScreen(self:GetWide())

  self.hover = vgui.Create(item.Hover)
  if (!IsValid(self.hover)) then self.hover = nil return end
  self.hover:SetPos(x, y)
  self.hover:SetDrawOnTop(true)
  self.hover.parent = self
  local oldThink = self.hover.Think or function() end
  self.hover.Think = function(pnl)
    oldThink(pnl)

    if (!self:IsHovered() and IsValid(pnl) or !IsValid(self)) then
      pnl:Remove()

      return
    end

    if (!IsValid(self)) then
      pnl:Remove()

      return
    end

    local w, h = pnl:GetSize()
    local x, y = pnl.x, pnl.y
    x = math.Clamp(x, 0, ScrW() - w)
    y = math.Clamp(y, 0, ScrH() - h)

    pnl:SetPos(x, y)
  end

  self.hover:SetInfo(self.info)
end

function PANEL:OnCursorExited()
  self:Lerp("overlayAlpha", 0)

  if IsValid(self.hover) then
    self.hover:Remove()
  end
end

function PANEL:Paint(w, h)
  if self:GetName() then

    XeninUI:Mask(function()
      XeninUI:DrawRoundedBox(6, 0, 0, w, h - 1, self:GetBackgroundColor())
    end, function()
      surface.SetDrawColor(self:GetBackgroundColor())
      surface.SetMaterial(matGradient)
      surface.DrawTexturedRect(0, 0, w, h + 6)
    end)

    draw.RoundedBoxEx(6, 0, h - 24, w, 24, self:GetNameColor(), false, false, true, true)
    local font = "XeninInventory.Field.Name"
    surface.SetFont(font)
    local tw, th = surface.GetTextSize(self:GetName())
    if (tw >= w) then
      surface.SetFont("XeninInventory.Field.Name.Small")
      local tw, th = surface.GetTextSize(self:GetName())
      if (tw >= w) then
        font = "XeninInventory.Field.Name.Smallest"
      else
        font = "XeninInventory.Field.Name.Small"
      end
    end
    draw.SimpleText(self:GetName(), font, w / 2, h - 24 / 2, self:GetNameTextColor(), TEXT_ALIGN_CENTER, TEXT_ALIGN_CENTER)
  else
    draw.RoundedBox(6, 0, 0, w, h, self:GetBackgroundColor())
  end

  if (self.overlayAlpha > 0.1) then
    draw.RoundedBox(6, 0, 0, w, h, Color(0, 0, 0, self.overlayAlpha))
  end
end

vgui.Register("XeninInventory.Field", PANEL, "DButton")
