zmlab2 = zmlab2 or {}
zmlab2.materials = zmlab2.materials or {}


zclib.Materials.Add("icon_bee", Material("materials/zerochain/zmlab2/ui/icon_bee.png", "smooth"))
zclib.Materials.Add("icon_acid", Material("materials/zerochain/zmlab2/ui/icon_acid.png", "smooth"))
zclib.Materials.Add("icon_alu", Material("materials/zerochain/zmlab2/ui/icon_alu.png", "smooth"))
zclib.Materials.Add("icon_lox", Material("materials/zerochain/zmlab2/ui/icon_lox.png", "smooth"))
zclib.Materials.Add("icon_cold", Material("materials/zerochain/zmlab2/ui/icon_cold.png", "smooth"))
zclib.Materials.Add("icon_hot", Material("materials/zerochain/zmlab2/ui/icon_hot.png", "smooth"))
zclib.Materials.Add("icon_error", Material("materials/zerochain/zmlab2/ui/icon_error.png", "smooth"))
zclib.Materials.Add("tank_overlay", Material("materials/zerochain/zmlab2/ui/tank_overlay.png", "smooth"))
zclib.Materials.Add("air_pressure_pointer", Material("materials/zerochain/zmlab2/ui/air_pressure_pointer.png", "smooth"))
zclib.Materials.Add("liquid_glow_top", Material("materials/zerochain/zmlab2/ui/liquid_glow_top.png", "smooth"))
zclib.Materials.Add("icon_sponge", Material("materials/zerochain/zmlab2/ui/icon_sponge.png", "smooth"))
zclib.Materials.Add("icon_pipe", Material("materials/zerochain/zmlab2/ui/icon_pipe.png", "smooth"))
zclib.Materials.Add("icon_pipe_smoke", Material("materials/zerochain/zmlab2/ui/icon_pipe_smoke.png", "smooth"))
zclib.Materials.Add("long_pipe", Material("materials/zerochain/zmlab2/ui/long_pipe.png", "smooth"))
zclib.Materials.Add("pipe_connect", Material("materials/zerochain/zmlab2/ui/pipe_connect.png", "smooth"))
zclib.Materials.Add("icon_fire_extinguisher", Material("materials/zerochain/zmlab2/ui/icon_fire_extinguisher.png", "smooth"))
zclib.Materials.Add("icon_fold", Material("materials/zerochain/zmlab2/ui/icon_fold.png", "smooth"))
zclib.Materials.Add("icon_light", Material("materials/zerochain/zmlab2/ui/icon_light.png", "smooth"))
zclib.Materials.Add("icon_tray", Material("materials/zerochain/zmlab2/ui/icon_tray.png", "smooth"))
zclib.Materials.Add("temp_bg", Material("materials/zerochain/zmlab2/ui/temp_bg.png", "smooth"))
zclib.Materials.Add("icon_liquid", Material("materials/zerochain/zmlab2/ui/icon_liquid.png", "smooth"))
zclib.Materials.Add("errorgame_overlay", Material("materials/zerochain/zmlab2/ui/errorgame_overlay.png", "smooth"))
zclib.Materials.Add("icon_pipe_off", Material("materials/zerochain/zmlab2/ui/icon_pipe_off.png", "smooth"))
zclib.Materials.Add("icon_pipe_on", Material("materials/zerochain/zmlab2/ui/icon_pipe_on.png", "smooth"))
zclib.Materials.Add("icon_meth", Material("materials/zerochain/zmlab2/ui/icon_meth.png", "smooth"))
zclib.Materials.Add("pipe_smoke01", Material("materials/zerochain/zmlab2/ui/pipe_smoke01.png", "smooth"))
zclib.Materials.Add("pipe_smoke02", Material("materials/zerochain/zmlab2/ui/pipe_smoke02.png", "smooth"))
zclib.Materials.Add("pipe_smoke03", Material("materials/zerochain/zmlab2/ui/pipe_smoke03.png", "smooth"))
zclib.Materials.Add("icon_locked_outline", Material("materials/zerochain/zmlab2/ui/icon_locked_outline.png", "smooth"))
zclib.Materials.Add("icon_breaking", Material("materials/zerochain/zmlab2/ui/breaking.png", "smooth"))
zclib.Materials.Add("icon_triangle", Material("materials/zerochain/zmlab2/ui/icon_triangle.png", "smooth"))

zmlab2.colors = zmlab2.colors or {}
zmlab2.colors["black04"] = Color(0, 0, 0, 240)
zmlab2.colors["white02"] = Color(255, 255, 255, 100)
zmlab2.colors["white03"] = Color(255, 255, 255, 15)
zmlab2.colors["green01"] = Color(0, 255, 0, 100)

zmlab2.colors["green03"] = Color(71, 209, 53, 255)
zmlab2.colors["blue01"] = Color(0, 125, 255, 100)
zmlab2.colors["blue02"] = Color(0, 125, 255, 255)
zmlab2.colors["grey01"] = Color(75, 75, 75, 255)
zmlab2.colors["grey02"] = Color(175, 175, 175, 255)
zmlab2.colors["acid"] = Color(150, 190, 71, 255)
zmlab2.colors["orange01"] = Color(255, 125, 0, 255)
zmlab2.colors["red01"] = Color(209, 53, 53, 100)
zmlab2.colors["red02"] = Color(209, 53, 53, 255)

zmlab2.colors["mixer_liquid01"] = Color(255, 230, 111, 255)
zmlab2.colors["mixer_liquid02"] = Color(186, 255, 111, 255)
zmlab2.colors["mixer_liquid05"] = Color(187, 230, 210, 255)
