-- I DO NOT ADVISE YOU TRY TO EDIT BELOW THIS LINE UNLESS YOU UNDERSTAND HOW THIS WORKS!
-- IF YOU WANT TO ADD A LANAGUE PLEASE OPEN A SUPPORT TICKET ON GMODSTORE.
-- I WILL HELP YOU WITH ANYTHING YOU NEED AND ADD THE LANGUAGE TO THE OFFICIAL SCRIPT.
CH_AdvMedic.Config.Lang = CH_AdvMedic.Config.Lang or {}

-- Ambulance NPC
CH_AdvMedic.Config.Lang["Ambulance Station"] = {
	["en"] = "Ambulance Station",
	["fr"] = "Station de l'ambulance",
	["da"] = "Ambulance Station",
	["de"] = "Ambulanzstation",
	["pl"] = "",
	["ru"] = "станция скорой помощи",
	["es"] = "Estación de ambulancias",
	["pt"] = "Estação de ambulância",
	["cn"] = "救护站",
	["it"] = "",
	["tr"] = "Ambulans Istasyonu",
}

CH_AdvMedic.Config.Lang["As a paramedic you can retrieve an ambulance from this NPC."] = {
	["en"] = "As a paramedic you can retrieve an ambulance from this NPC.",
	["fr"] = "En tant qu'ambulancier, vous pouvez récupérer une ambulance auprès de ce PNJ.",
	["da"] = "Som paramediciner kan du hente en ambulance fra denne NPC.",
	["de"] = "Als Sanitäter kannst du dir von diesem NPC einen Krankenwagen abholen.",
	["pl"] = "",
	["ru"] = "Как Парамедик вы можете получить машину скорую помощи от этого NPC.",
	["es"] = "Como paramédico, podrá retirar una ambulancia desde este NPC.",
	["pt"] = "Como paramédico, você pode recuperar uma ambulância desse NPC.",
	["cn"] = "作为救护人员，你可以从NPC那里存取一辆救护车。",
	["it"] = "",
	["tr"] = "Saglik personeliyken bu NPC'den ambulans çikarabilirsin.",
}
CH_AdvMedic.Config.Lang["Use it to quickly get to people who need to be healed."] = {
	["en"] = "Use it to quickly get to people who need to be healed.",
	["fr"] = "Utilisez-le pour atteindre rapidement les personnes qui ont besoin d'être guéries.",
	["da"] = "Brug den til hurtigt at komme frem og hjælpe spillere der skal helbredes.",
	["de"] = "Benutze den Krankenwagen um schnell zu Leuten, die Hilfe brauchen zu gelangen",
	["pl"] = "",
	["ru"] = "Используйте его, чтобы быстро добраться до людей, которых нужно вылечить",
	["es"] = "Úsala para llegar rápido a situaciones que requieran curar a las personas.",
	["pt"] = "Use-o para chegar rapidamente a pessoas que precisam ser curadas.",
	["cn"] = "用它来迅速到达需要治疗的人。",
	["it"] = "",
	["tr"] = "Tedaviye ihtiyaci olan insanlara hizla ulasmak için kullan.",
}
CH_AdvMedic.Config.Lang["You are equipped with a medkit."] = {
	["en"] = "You are equipped with a medkit.",
	["fr"] = "Vous êtes équipé d'un kit de soin.",
	["da"] = "Du er udstyret med et medkit.",
	["de"] = "Du bist mit einem Medkit ausgerüstet.",
	["pl"] = "",
	["ru"] = "Вы экипированы аптечкой.",
	["es"] = "Te has equipado un kit de primeros auxilios.",
	["pt"] = "Você está equipado com um kit médico.",
	["cn"] = "你装备了一个医疗包。",
	["it"] = "",
	["tr"] = "Ekipmaninda ilk yardim çantasi bulunuyor.",
}
CH_AdvMedic.Config.Lang["Click here to retrieve an ambulance."] = {
	["en"] = "Click here to retrieve an ambulance.",
	["fr"] = "Cliquez ici pour récupérer une ambulance.",
	["da"] = "Klik her for at hente en ambulance.",
	["de"] = "Klicke hier um einen Krankenwagen auszuparken",
	["pl"] = "",
	["ru"] = "Нажмите здесь, чтобы получить машину скорую помощи.",
	["es"] = "Click aquí para retirar una ambulancia.",
	["pt"] = "Clique aqui para recuperar uma ambulância.",
	["cn"] = "单击此处取出救护车。",
	["it"] = "",
	["tr"] = "Buraya tıklayarak bir ambulans al.",
}
CH_AdvMedic.Config.Lang["Click here to remove your current ambulance."] = {
	["en"] = "Click here to remove your current ambulance.",
	["fr"] = "Cliquez ici pour supprimer votre ambulance actuelle.",
	["da"] = "Klik her for at fjerne din nuværende ambulance.",
	["de"] = "Klicke hier, um deinen jetzigen Krankenwagen zu entfernen",
	["pl"] = "",
	["ru"] = "Нажмите здесь, чтобы удалить вашу текущую машину скорую помощи.",
	["es"] = "Click aquí para devolver tu ambulancia.",
	["pt"] = "Clique aqui para remover sua ambulância atual.",
	["cn"] = "单击此处收回当前的救护车。",
	["it"] = "",
	["tr"] = "Buraya tıklayarak ambulansı kaldır.",
}

CH_AdvMedic.Config.Lang["Retrieve"] = {
	["en"] = "Retrieve",
	["fr"] = "Récupérer",
	["da"] = "Hent",
	["de"] = "Ausparken",
	["pl"] = "",
	["ru"] = "получить",
	["es"] = "Retirar",
	["pt"] = "Recuperar",
	["cn"] = "取出",
	["it"] = "",
	["tr"] = "Geri Al",
}
CH_AdvMedic.Config.Lang["Remove"] = {
	["en"] = "Remove",
	["fr"] = "Supprimer",
	["da"] = "Fjern",
	["de"] = "Einparken",
	["pl"] = "",
	["ru"] = "удалить",
	["es"] = "Devolver",
	["pt"] = "Retirar",
	["cn"] = "收回",
	["it"] = "",
	["tr"] = "Sil",
}
CH_AdvMedic.Config.Lang["Only paramedics can access this NPC!"] = {
	["en"] = "Only paramedics can access this NPC!",
	["fr"] = "Seulement les médecins peuvent acceder à ce PNJ!",
	["da"] = "Kun paramedicinere har adgang til denne NPC!",
	["de"] = "Nur Sanitäter haben zugriff auf diesen NPC!",
	["pl"] = "",
	["ru"] = "Только парамедики могут получить доступ к этому NPC!",
	["es"] = "¡Sólo los paramédicos pueden acceder a este NPC!",
	["pt"] = "Apenas paramédicos podem acessar este NPC!",
	["cn"] = "只有医护人员可以使用这个NPC!",
	["it"] = "",
	["tr"] = "Sadece sağlık personelleri bu NPC'ye erişebilir!",
}

-- Ambulance NPC Actions (Serverside)
CH_AdvMedic.Config.Lang["You already own an ambulance!"] = {
	["en"] = "You already own an ambulance!",
	["fr"] = "Vous possédez déjà une ambulance!",
	["da"] = "Du ejer allerede en ambulance!",
	["de"] = "Du besitzt bereits einen Krankenwagen!",
	["pl"] = "",
	["ru"] = "У вас уже есть машину скорую помощи!",
	["es"] = "¡Ya tienes una ambulancia!",
	["pt"] = "Você já possui uma ambulância!",
	["cn"] = "你已经有一辆救护车了!",
	["it"] = "",
	["tr"] = "Zaten bir ambulans çıkarıldı!",
}
CH_AdvMedic.Config.Lang["The limitation of maximum ambulances has been reached!"] = {
	["en"] = "The limitation of maximum ambulances has been reached!",
	["fr"] = "La limitation du nombre maximum d'ambulances a été atteinte!",
	["da"] = "Den maksimale grænse af ambulancer er nået!",
	["de"] = "Das Limit der verfügbaren Krankenwagen ist erreicht!",
	["pl"] = "",
	["ru"] = "Достигнуто максимальное количество машину скорую помощи!",
	["es"] = "¡El límite de ambulancias fue alcanzado!",
	["pt"] = "A limitação do número máximo de ambulâncias foi atingida!",
	["cn"] = "救护车已经达到最大限度!",
	["it"] = "",
	["tr"] = "Maksimum ambulans limitine ulaştın!",
}
CH_AdvMedic.Config.Lang["Your current ambulance has been removed!"] = {
	["en"] = "Your current ambulance has been removed!",
	["fr"] = "Votre ambulance actuelle à été supprimé!",
	["da"] = "Din nuværende ambulance er blevet fjernet!",
	["de"] = "Dein aktueller Krankenwagen wurde entfernt!",
	["pl"] = "",
	["ru"] = "Ваша текущая машину скорую помощи была удалена!",
	["es"] = "Tu ambulancia ha sido devuelta.",
	["pt"] = "Sua ambulância atual foi removida!",
	["cn"] = "你的救护车被收回了！",
	["it"] = "",
	["tr"] = "Mevcut ambulans kaldırıldı!",
}
CH_AdvMedic.Config.Lang["You don't have an ambulance!"] = {
	["en"] = "You don't have an ambulance!",
	["fr"] = "Vous n'avez pas d'ambulance!",
	["da"] = "Du har ikke en ambulance!",
	["de"] = "Du hast keinen Krankenwagen!",
	["pl"] = "",
	["ru"] = "У тебя нет машины скорой помощи!",
	["es"] = "¡No tienes una ambulancia!",
	["pt"] = "Você não tem ambulância!",
	["cn"] = "你没有救护车!",
	["it"] = "",
	["tr"] = "Ambulans çıkarmadın!",
}
CH_AdvMedic.Config.Lang["You have succesfully retrieved an ambulance! It's parked right outside the building."] = {
	["en"] = "You have succesfully retrieved an ambulance! It's parked right outside the building.",
	["fr"] = "Vous avez récupérer avec succès une ambulance! Elle est garé juste devant le bâtiment.",
	["da"] = "Du har med succes hentet en ambulance! Den er parkeret lige uden foran bygningen.",
	["de"] = "",
	["pl"] = "",
	["ru"] = "Вы успешно забрали машину скорой помощи! Она припаркована прямо возле здания.",
	["es"] = "Has retirado una ambulancia. Está estacionada fuera del establecimiento.",
	["pt"] = "Você recuperou uma ambulância com sucesso! Está estacionado em frente ao prédio.",
	["cn"] = "你成功地生成了一辆救护车!就停在医院外面。",
	["it"] = "",
	["tr"] = "Başarıyla ambulans çıkarıldı. Binanın hemen dışına park edildi.",
}


-- Health/Armor NPC
CH_AdvMedic.Config.Lang["Hospital"] = {
	["en"] = "Hospital",
	["fr"] = "Hôpital",
	["da"] = "Hospital",
	["de"] = "Krankenhaus",
	["pl"] = "",
	["ru"] = "больница",
	["es"] = "Hospital",
	["pt"] = "Hospital",
	["cn"] = "医院",
	["it"] = "",
	["tr"] = "Hastane",
}
CH_AdvMedic.Config.Lang["Hey there,"] = {
	["en"] = "Hey there,",
	["fr"] = "Bonjour,",
	["da"] = "Hejsa,",
	["de"] = "Hallo,",
	["pl"] = "",
	["ru"] = "Привет,",
	["es"] = "Buenos días,",
	["pt"] = "Olá,",
	["cn"] = "嘿，",
	["it"] = "",
	["tr"] = "Merhaba,",
}
CH_AdvMedic.Config.Lang["If you are hurt I can help patch you up."] = {
	["en"] = "If you are hurt I can help patch you up.",
	["fr"] = "Si vous êtes blessé, je peux aider à vous soigner",
	["da"] = "Hvis du er såret, kan jeg hjælpe med at helbrede dig.",
	["de"] = "Wenn du verletzt bist, kann ich dir Helfen dich zu verarzten",
	["pl"] = "",
	["ru"] = "Если тебе больно, я могу помочь залатать тебя.",
	["es"] = "Si estás herido, puedo ayudarte.",
	["pt"] = "Se você se machucar, posso ajudá-lo.",
	["cn"] = "如果你受伤了，我可以帮助你。",
	["it"] = "",
	["tr"] = "Eger yaraliysan, iyilesmeni saglayabilirim.",
}
CH_AdvMedic.Config.Lang["Just let me know which type of healing you need."] = {
	["en"] = "Just let me know which type of healing you need.",
	["fr"] = "Faites-moi simplement savoir quel type de soin vous avez besoin.",
	["da"] = "Bare lad mig vide, hvilken type heldbredning du har brug for.",
	["de"] = "Lass mich wissen welche Art von Medizin du benötigst!",
	["pl"] = "",
	["ru"] = "Просто дайте мне знать, какой тип лечения вам нужно.",
	["es"] = "Sólo dime qué tipo de heridas necesitas sanar.",
	["pt"] = "Deixe-me saber que tipo de cura você precisa.",
	["cn"] = "请告诉我，你需要治疗什么部位。",
	["it"] = "",
	["tr"] = "Sadece bana hangi tür saglik hizmetine ihtiyacin oldugunu söyle.",
}
CH_AdvMedic.Config.Lang["Purchase Health"] = {
	["en"] = "Purchase Health",
	["fr"] = "Acheter de la santé",
	["da"] = "Køb Liv",
	["de"] = "Heilung Kaufen",
	["pl"] = "",
	["ru"] = "Покупка здоровья",
	["es"] = "Comprar medicamentos",
	["pt"] = "Comprar vida",
	["cn"] = "购买医疗包",
	["it"] = "",
	["tr"] = "CAN",
}
CH_AdvMedic.Config.Lang["Purchase Armor"] = {
	["en"] = "Purchase Armor",
	["fr"] = "Acheter de l'armure",
	["da"] = "Køb Rustning",
	["de"] = "Rüstung Kaufen",
	["pl"] = "",
	["ru"] = "Купить броню",
	["es"] = "Comprar armadura",
	["pt"] = "Comprar Armadura",
	["cn"] = "购买护甲",
	["it"] = "",
	["tr"] = "ZIRH",
}
CH_AdvMedic.Config.Lang["Price:"] = {
	["en"] = "Price:",
	["fr"] = "Prix:",
	["da"] = "Pris:",
	["de"] = "Preis:",
	["pl"] = "",
	["ru"] = "Цена:",
	["es"] = "Precio:",
	["pt"] = "Preço:",
	["cn"] = "价格：",
	["it"] = "",
	["tr"] = "Fiyat:",
}

-- Health NPC Actions (Serverside)
CH_AdvMedic.Config.Lang["The minimum required paramedics for this service to be available is"] = {
	["en"] = "The minimum required paramedics for this service to be available is",
	["fr"] = "Le nombre minimum de médecins requis pour que ce service soit disponible est de",
	["da"] = "Der kræves et minimum af paramediciner før denne service virker: ",
	["de"] = "Die minimal benötigte anzahl an Sanitätern, für diesen Service ist",
	["pl"] = "",
	["ru"] = "Минимальная необходимая медицинская помощь для этой услуги",
	["es"] = "El mínimo de paramédicos requeridos para este servicio son",
	["pt"] = "O minimo de paramedicos para que este serviço esteja disponível é",
	["cn"] = "提供这项服务所需的最低医生人数为",
	["it"] = "",
	["tr"] = "Bu hizmetin kullanılabilmesi için gereken minimum sağlık personeli",
}
CH_AdvMedic.Config.Lang["You can only use this service if there are no paramedics on duty!"] = {
	["en"] = "You can only use this service if there are no paramedics on duty!",
	["fr"] = "Vous ne pouvez utiliser ce service que s'il n'y a pas d'ambulanciers en service!",
	["da"] = "Du kan kun bruge denne service, hvis der ikke er nogen paramediciner på vagt!",
	["de"] = "Sie können diesen Service nur nutzen, wenn keine Sanitäter im Einsatz sind!",
	["pl"] = "",
	["ru"] = "Воспользоваться этой услугой можно только при отсутствии дежурных медработников!",
	["es"] = "¡Solo puede utilizar este servicio si no hay paramédicos de servicio!",
	["pt"] = "Você só pode usar este serviço se não houver paramédicos de plantão!",
	["cn"] = "您只有在没有值班医护人员的情况下才能使用此服务！",
	["it"] = "",
	["tr"] = "Bu hizmeti yalnızca görevli sağlık personeli olmadığında kullanabilirsin!",
}
CH_AdvMedic.Config.Lang["You are too far away from the NPC!"] = {
	["en"] = "You are too far away from the NPC!",
	["fr"] = "Vous êtes trop loin du NPC!",
	["da"] = "Du er for langt væk fra NPC!",
	["de"] = "Du bist zu weit vom NPC entfernt!",
	["pl"] = "",
	["ru"] = "Вы слишком далеко от NPC!",
	["es"] = "¡Estás demasiado lejos del NPC!",
	["pt"] = "Você está muito longe do NPC!",
	["cn"] = "你离NPC太远了！",
	["it"] = "",
	["tr"] = "NPC'den çok uzaktasın!",
}
CH_AdvMedic.Config.Lang["The server has disabled this feature!"] = {
	["en"] = "The server has disabled this feature!",
	["fr"] = "Le serveur a désactivé cette fonctionnalité !",
	["da"] = "Serveren har deaktiveret denne funktion!",
	["de"] = "Der Server hat diese Funktion deaktiviert!",
	["pl"] = "",
	["ru"] = "Сервер отключил эту функцию!",
	["es"] = "¡El servidor ha desactivado esta función!",
	["pt"] = "O servidor desativou este recurso!",
	["cn"] = "服务器已禁用此功能！",
	["it"] = "",
	["tr"] = "Sunucu bu özelliği devre dışı bıraktı!",
}
CH_AdvMedic.Config.Lang["Your health is already at maximum."] = {
	["en"] = "Your health is already at maximum.",
	["fr"] = "Votre santé est déjà maximale.",
	["da"] = "Dit helbred er allerede så godt, som det kan være.",
	["de"] = "Du hast bereits das maximum an Gesundheit!",
	["pl"] = "",
	["ru"] = "Ваше здоровье уже на максимуме.",
	["es"] = "Tu vida ya está al máximo.",
	["pt"] = "Sua saúde já está no máximo.",
	["cn"] = "你的健康状况已经达到了最佳状态。",
	["it"] = "",
	["tr"] = "Sağlığın zaten dolu.",
}
CH_AdvMedic.Config.Lang["Your armor is already at maximum."] = {
	["en"] = "Your armor is already at maximum.",
	["fr"] = "Votre armure est déjà maximale.",
	["da"] = "Din rustning er allerede fuldt intakt.",
	["de"] = "Du hast bereits das maximum an Rüstung!",
	["pl"] = "",
	["ru"] = "Ваша броня уже на максимуме.",
	["es"] = "Tu armadura ya está al máximo.",
	["pt"] = "Sua armadura já está no máximo.",
	["cn"] = "你的护甲值已经满了。",
	["it"] = "",
	["tr"] = "Zırhın zaten maksimumda.",
}
CH_AdvMedic.Config.Lang["Your health has been refilled. You have been charged"] = {
	["en"] = "Your health has been refilled. You have been charged",
	["fr"] = "Votre vie a été rempli. Vous avez été prélevé de",
	["da"] = "Dit liv er blevet genopfyldt. Du er blevet debiteret",
	["de"] = "Deine Gesundheit wurde wieder aufgefüllt, dir wurde Geld abgezogen!",
	["pl"] = "",
	["ru"] = "Ваше здоровье пополнилось. Вы заплатили",
	["es"] = "Tu vida ha sido recargada. Se te ha cobrado",
	["pt"] = "Sua saúde foi reabastecida. Você foi cobrado",
	["cn"] = "你的生命值已经恢复了，医院已向你收取费用，",
	["it"] = "",
	["tr"] = "Sağlığınız yenilendi. Ödeme alındı",
}
CH_AdvMedic.Config.Lang["Your armor has been refilled. You have been charged"] = {
	["en"] = "Your armor has been refilled. You have been charged",
	["fr"] = "Votre armure a été rempli. Vous avez été prélevé de",
	["da"] = "Din rustning er blevet fuldt forstærket. Du er blevet debiteret",
	["de"] = "Deine Rüstung wurde wieder aufgefüllt, dir wurde Geld abgezogen!",
	["pl"] = "",
	["ru"] = "Ваша броня была пополнена. Вы заплатили",
	["es"] = "Tu armadura ha sido recargada. Se te ha cobrado.",
	["pt"] = "Sua armadura foi recarregada. Você foi cobrado",
	["cn"] = "你的护甲值被补满了，医院已向你收取费用。",
	["it"] = "",
	["tr"] = "Zırhın yenilendi. Ödeme alındı",
}
CH_AdvMedic.Config.Lang["You cannot afford this!"] = {
	["en"] = "You cannot afford this!",
	["fr"] = "Vous n'avez pas les fonds nécessaires!",
	["da"] = "Du har ikke råd til dette!",
	["de"] = "Du kannst dir das nicht leisten!",
	["pl"] = "",
	["ru"] = "Вы не можете себе этого позволить!",
	["es"] = "¡No puedes pagar esto!",
	["pt"] = "Você não pode pagar isso!",
	["cn"] = "你支付不起！",
	["it"] = "",
	["tr"] = "Bunu karşılayamazsın!",
}

-- Health Kit Weapon
CH_AdvMedic.Config.Lang["Left Click: Heal target, Right Click: Heal yourself"] = {
	["en"] = "Left Click: Heal target, Right Click: Heal yourself",
	["fr"] = "Clique Gauche: Soigner la cible, Clique Droit: Se soigner",
	["da"] = "Venstreklik: Helbred mål, Højreklik: Helbred dig selv",
	["de"] = "Linksklick: Ziel Heilen, Rechtsklick: Dich selbst Heilen",
	["pl"] = "",
	["ru"] = "Левый клик: исцелить цель, правый клик: исцелить себя",
	["es"] = "Click izquierdo: Curar objetivo, Click derecho: Curarte a tí mismo",
	["pt"] = "Clique esquerdo: curar o alvo, clique direito: curar a si mesmo",
	["cn"] = "左键:治疗目标，右键:治疗你自己",
	["it"] = "",
	["tr"] = "Sol tık: Hedefi iyileştir\nSağ tık: Kendini iyileştir",
}
CH_AdvMedic.Config.Lang["Health Kit"] = {
	["en"] = "Health Kit",
	["fr"] = "Kit de Soin",
	["da"] = "Health Kit",
	["de"] = "Sanitätstasche",
	["pl"] = "",
	["ru"] = "Аптечка",
	["es"] = "Kit de primeros auxilios",
	["pt"] = "Kit Saúde",
	["cn"] = "医疗包",
	["it"] = "",
	["tr"] = "İlk Yardım Çantası",
}
CH_AdvMedic.Config.Lang["Charge:"] = {
	["en"] = "Charge:",
	["fr"] = "Charge:",
	["da"] = "Opladt:",
	["de"] = "Ladung:",
	["pl"] = "",
	["ru"] = "пополнить:",
	["es"] = "Carga:",
	["pt"] = "Carregar:",
	["cn"] = "充能：",
	["it"] = "",
	["tr"] = "Şarj:",
}
CH_AdvMedic.Config.Lang["You must move closer to the target to heal them."] = {
	["en"] = "You must move closer to the target to heal them.",
	["fr"] = "Vous devez vous rapprocher de la cible pour la soigner.",
	["da"] = "Du skal komme nærmere målet for at helbrede dem.",
	["de"] = "Du must näher an das Ziel rangehen, um eine Person zu heilen.",
	["pl"] = "",
	["ru"] = "Вы должны приблизиться к цели ближе, чтобы излечить",
	["es"] = "Debes moverte cerca del objetivo para curarlo.",
	["pt"] = "Você deve se aproximar do alvo para curá-los.",
	["cn"] = "你必须靠近目标来治疗它们。",
	["it"] = "",
	["tr"] = "Hedefi iyileştirmek için yakınlaşman gerekiyor.",
}

-- Recharge Station
CH_AdvMedic.Config.Lang["The recharge stations has been refilled with new charges!"] = {
	["en"] = "The recharge stations has been refilled with new charges!",
	["fr"] = "La station de recharge a été rechargée avec de nouvelles charges!",
	["da"] = "Opladningsstationerne er blevet genopfyldt med nye opladninger!",
	["de"] = "Die Ladestation wurde mit neuen Ladungen aufgefüllt!",
	["pl"] = "",
	["ru"] = "Зарядная станция пополнилась новыми расходами!",
	["es"] = "¡La estación de recarga ha sido recargada!",
	["pt"] = "A estação de recarga foi recarregada com novas cobranças!",
	["cn"] = "充能站已经重新充能完毕!",
	["it"] = "",
	["tr"] = "Şarj istasyonları yeniden dolduruldu!",
}

-- Armor Entities
CH_AdvMedic.Config.Lang["You've reached the maximum amount of armor that you can have!"] = {
	["en"] = "You've reached the maximum amount of armor that you can have!",
	["fr"] = "Vous avez atteint le maximum d'armure que vous pouvez avoir!",
	["da"] = "Din rustning af ved dens maksimale styrke!",
	["de"] = "Du hast die maximale Anzahl an Rüstung erreicht!",
	["pl"] = "",
	["ru"] = "Вы достигли максимально возможного количества брони!",
	["es"] = "¡Has alcanzado el máximo de armadura que puedes tener!",
	["pt"] = "Você atingiu a quantidade máxima de armadura que pode ter!",
	["cn"] = "你已经达到了你所能拥有的最大护甲值!",
	["it"] = "",
	["tr"] = "Sahip olabileceğin maksimum zırh miktarına ulaştın!",
}
CH_AdvMedic.Config.Lang["Your armor has been filled to the maximum!"] = {
	["en"] = "Your armor has been filled to the maximum!",
	["fr"] = "Votre armure a été remplie au maximum!",
	["da"] = "Din rustning er blevet forstærket til maksimum.",
	["de"] = "Deine Rüstung wurde komplett aufgefüllt!",
	["pl"] = "",
	["ru"] = "Ваша броня была заполнена по максимуму!",
	["es"] = "¡Tu armadura ha sido cargada al máximo!",
	["pt"] = "Sua armadura foi preenchida ao máximo!",
	["cn"] = "你的护甲已满载！",
	["it"] = "",
	["tr"] = "Zırhınız maksimum seviyeye kadar dolduruldu!",
}
CH_AdvMedic.Config.Lang["Armor"] = {
	["en"] = "Armor",
	["fr"] = "Armure",
	["da"] = "Rustning",
	["de"] = "Rüstung",
	["pl"] = "",
	["ru"] = "броня",
	["es"] = "Armadura",
	["pt"] = "armaduras",
	["cn"] = "护甲",
	["it"] = "",
	["tr"] = "Zırh",
}
CH_AdvMedic.Config.Lang["Armor Kit"] = {
	["en"] = "Armor Kit",
	["fr"] = "Kit d'Armure",
	["da"] = "Rustning",
	["de"] = "Rüstungsset",
	["pl"] = "",
	["ru"] = "Комплект брони",
	["es"] = "Kit de Armadura",
	["pt"] = "Kit de armadura",
	["cn"] = "护甲包",
	["it"] = "",
	["tr"] = "Zırh Kiti",
}

-- Health Kit Entities
CH_AdvMedic.Config.Lang["You've reached the maximum amount of health that you can have!"] = {
	["en"] = "You've reached the maximum amount of health that you can have!",
	["fr"] = "Vous avez atteint le maximum de points de vie que vous pouvez avoir!",
	["da"] = "Du har nået det maksimale liv du kan have!",
	["de"] = "Du hast bereits Maximale Anzahl an Gesundheitspunkten!",
	["pl"] = "",
	["ru"] = "Вы достигли максимально возможного количества здоровья!",
	["es"] = "¡Has alcanzado el límite máximo de vida que puedes tener!",
	["pt"] = "Você atingiu a quantidade máxima de saúde que pode ter!",
	["cn"] = "您已经达到了可以达到的最大健康水平！",
	["it"] = "",
	["tr"] = "Sahip olabileceğin maksimum sağlık miktarına ulaştın!",
}
CH_AdvMedic.Config.Lang["Your health has been filled to the maximum!"] = {
	["en"] = "Your health has been filled to the maximum!",
	["fr"] = "Votre vie a été remplie au maximum!",
	["da"] = "Dit helbred er så godt, som det kan være!",
	["de"] = "Du wurdest komplett geheilt!",
	["pl"] = "",
	["ru"] = "Ваше здоровье заполнено по максимуму!",
	["es"] = "¡Tu vida ha sido cargada al máximo!",
	["pt"] = "Sua saúde foi preenchida ao máximo!",
	["cn"] = "你已经到达了职业生命值的上限！",
	["it"] = "",
	["tr"] = "Sağlığın tamamen doldu!",
}
CH_AdvMedic.Config.Lang["Health"] = {
	["en"] = "Health",
	["fr"] = "Santé",
	["da"] = "Helbred",
	["de"] = "Gesungheit",
	["pl"] = "",
	["ru"] = "Здоровье",
	["es"] = "Vida",
	["pt"] = "Saúde",
	["cn"] = "生命值",
	["it"] = "",
	["tr"] = "Sağlık",
}
CH_AdvMedic.Config.Lang["Health Kit"] = {
	["en"] = "Health Kit",
	["fr"] = "Kit de Soin",
	["da"] = "Health Kit",
	["de"] = "Sanitätstasche",
	["pl"] = "",
	["ru"] = "Аптечка",
	["es"] = "Kit de primeros auxilios",
	["pt"] = "Kit Saúde",
	["cn"] = "医疗包",
	["it"] = "",
	["tr"] = "İlk Yardım Çantası",
}

-- Recharge Station
CH_AdvMedic.Config.Lang["There are no recharges available at this moment!"] = {
	["en"] = "There are no recharges available at this moment!",
	["fr"] = "Il n'y a pas de recharges disponibles pour le moment!",
	["da"] = "Der er ingen opladninger tilgængelige i øjeblikket!",
	["de"] = "Derzeit sind keine Ladungen verfügbar!",
	["pl"] = "",
	["ru"] = "На данный момент нет доступных пополнений!",
	["es"] = "¡No hay recargas disponibles actualmente!",
	["pt"] = "Não há recargas disponíveis no momento!",
	["cn"] = "目前没有任何充能服务!",
	["it"] = "",
	["tr"] = "Şu anda kullanılabilir şarj yok!",
}
CH_AdvMedic.Config.Lang["Your medkit has been fully recharged!"] = {
	["en"] = "Your medkit has been fully recharged!",
	["fr"] = "Votre kit de soin a été entièrement rechargé!",
	["da"] = "Dit medkit er blevet genopladet!",
	["de"] = "Deine Sanitätstasche wurde komplett aufgefüllt!",
	["pl"] = "",
	["ru"] = "Ваша аптечка была полностью перезаряжена!",
	["es"] = "¡Tu kit ha sido recargado!",
	["pt"] = "Seu kit medico foi totalmente recarregado!",
	["cn"] = "你的医疗包已经充能完毕!",
	["it"] = "",
	["tr"] = "İlk yardım çantan tamamen dolduruldu!",
}
CH_AdvMedic.Config.Lang["You can only recharge your medkit when it's under"] = {
	["en"] = "You can only recharge your medkit when it's under",
	["fr"] = "Vous ne pouvez recharger votre kit de soin que lorsqu'il est en dessous de",
	["da"] = "Du kan kun oplade dit medkit, når den er under",
	["de"] = "Du kannst deine Sanitätstasche nur auffüllen wenn du unter %%%% Ladungen hast",
	["pl"] = "",
	["ru"] = "Зарядить аптечку можно только тогда, когда она",
	["es"] = "Sólo puedes recargar tu kit cuando esté bajo de",
	["pt"] = "Você só pode recarregar o seu kit medico quando estiver baixo",
	["cn"] = "你只能在医疗包能量不足时为其充能",
	["it"] = "",
	["tr"] = "İlk yardım çantanı ancak şunun altındayken şarj edebilirsin",
}
CH_AdvMedic.Config.Lang["You need to equip the medkit to recharge it!"] = {
	["en"] = "You need to equip the medkit to recharge it!",
	["fr"] = "Vous devez équiper le kit de soin pour le recharger!",
	["da"] = "Du skal trække dit medkit ud for at oplade det!",
	["de"] = "Du musst die Sanitätstasche ausrüsten um sie aufzufüllen",
	["pl"] = "",
	["ru"] = "Вам нужно оборудовать аптечку, чтобы перезарядить ее!",
	["es"] = "¡Debes equipar tu kit para recargarlo!",
	["pt"] = "Você precisa equipar o kit medico para recarregá-lo!",
	["cn"] = "你需要手持医疗包来给它充能!",
	["it"] = "",
	["tr"] = "İlk yardım çantanı şarj etmek için kuşanman lazım!",
}
CH_AdvMedic.Config.Lang["Only paramedics can use the recharge station!"] = {
	["en"] = "Only paramedics can use the recharge station!",
	["fr"] = "Seulement les médecins peuvent utiliser la station de recharge!",
	["da"] = "Kun paramedicinere kan bruge genopladningsstationen!",
	["de"] = "Nur Sanitäter können die Ladestation benutzen!",
	["pl"] = "",
	["ru"] = "Только парамедики могут использовать зарядную станцию!",
	["es"] = "¡Sólo los paramédicos pueden usar la estación de recarga!",
	["pt"] = "Apenas paramédicos podem usar a estação de recarga!",
	["cn"] = "只有医护人员可以使用充能站!",
	["it"] = "",
	["tr"] = "Sadece sağlık personelleri şarj istasyonunu kullanabilir!",
}

-- Recharge Station Display
CH_AdvMedic.Config.Lang["Recharge Station"] = {
	["en"] = "Recharge Station",
	["fr"] = "Station de Recharge",
	["da"] = "Genopladningsstation",
	["de"] = "Ladestation",
	["pl"] = "",
	["ru"] = "Станция перезарядки",
	["es"] = "Estación de Recarga",
	["pt"] = "Estação de recarga",
	["cn"] = "充能站",
	["it"] = "",
	["tr"] = "Şarj İstasyonu",
}
CH_AdvMedic.Config.Lang["Recharges Available"] = {
	["en"] = "Recharges Available",
	["fr"] = "Recharges Disponibles",
	["da"] = "Opladninger Tilgængelige",
	["de"] = "Ladungen verfügbar",
	["pl"] = "",
	["ru"] = "Доступны перезарядки",
	["es"] = "Recargas disponibles",
	["pt"] = "Recargas disponíveis",
	["cn"] = "充能站使用中",
	["it"] = "",
	["tr"] = "Mevcut Şarjlar",
}
CH_AdvMedic.Config.Lang["Left"] = {
	["en"] = "Left",
	["fr"] = "Restantes",
	["da"] = "Tilbage",
	["de"] = "Übrig",
	["pl"] = "",
	["ru"] = "Осталось",
	["es"] = "Restantes",
	["pt"] = "Esquerda",
	["cn"] = "剩余",
	["it"] = "",
	["tr"] = "Kaldı",
}
CH_AdvMedic.Config.Lang["Press 'e' to recharge"] = {
	["en"] = "Press 'e' to recharge",
	["fr"] = "Appuie sur 'e' pour recharger",
	["da"] = "Tryk 'e' for at oplade",
	["de"] = "Drücke 'e' um deine Ladungen aufzufüllen",
	["pl"] = "",
	["ru"] = "Нажмите 'е', чтобы пополнить",
	["es"] = "Presiona 'e' para recargar",
	["pt"] = "Clicar 'e' para recarregar ",
	["cn"] = "按下使用键充能",
	["it"] = "",
	["tr"] = "Yeniden şarj etmek için 'e' tuşuna bas",
}
CH_AdvMedic.Config.Lang["Only to be used by paramedics"] = {
	["en"] = "Only to be used by paramedics",
	["fr"] = "Peut être utiliser uniquement par les médecins",
	["da"] = "Må kun bruges af paramediciner",
	["de"] = "nur von Sanitätern zu verwenden",
	["pl"] = "",
	["ru"] = "Только для использования парамедиками",
	["es"] = "Sólo para ser usado por paramédicos",
	["pt"] = "Somente paramedicos podem usar",
	["cn"] = "只能由医护人员使用",
	["it"] = "",
	["tr"] = "Sadece sağlık personelleri",
}

-- Defibrillatrs
CH_AdvMedic.Config.Lang["Left Click: Use defib (charge required), Right Click: Charge defib"] = {
	["en"] = "Left Click: Use defib (charge required), Right Click: Charge defib",
	["fr"] = "Clique Gauche: Utiliser le défibrillateur (charge requise), Clique Droite: Charger le défibrillateur",
	["da"] = "Venstreklik: Brug hjertestarter (opladning nødvendig), Højre klik: Oplad hjertestarter",
	["de"] = "Linksklick: Defib verwenden (Gebühr erforderlich), Rechtsklick: Defib laden",
	["pl"] = "",
	["ru"] = "Левый клик: Использовать дефибриллятор (требуется зарядка), Правый клик: Заряжать дефибриллятор",
	["es"] = "Clic izquierdo: usar defib (se requiere carga), clic derecho: cargar defib",
	["pt"] = "Clique esquerdo: use defib (cobrança obrigatória), clique direito: carregue defib",
	["cn"] = "左键：使用除颤器（需要充电），右键：充电除颤器",
	["it"] = "",
	["tr"] = "Sol tık: Defibrilatör kullan (şarj gereklidir)\nSağ tık: Defibrilatör şarj et",
}
CH_AdvMedic.Config.Lang["Defibrillator"] = {
	["en"] = "Defibrillator",
	["fr"] = "Défibrillateur",
	["da"] = "Hjertestarter",
	["de"] = "Defibrillator",
	["pl"] = "",
	["ru"] = "дефибриллятор",
	["es"] = "Desfibrilador",
	["pt"] = "Desfibrilador",
	["cn"] = "除颤器",
	["it"] = "",
	["tr"] = "Defibrilatör",
}
CH_AdvMedic.Config.Lang["You need to move closer to the body."] = {
	["en"] = "You need to move closer to the body.",
	["fr"] = "Vous devez vous rapprocher du corps.",
	["da"] = "Du er nød til at komme tættere på liget.",
	["de"] = "Sie müssen näher an den Körper heranrücken.",
	["pl"] = "",
	["ru"] = "Вам нужно приблизиться к телу.",
	["es"] = "Necesitas acercarte a la persona.",
	["pt"] = "Você precisa se aproximar do corpo.",
	["cn"] = "你需要靠近昏迷的玩家。",
	["it"] = "",
	["tr"] = "Bedene yaklaşman gerek.",
}
CH_AdvMedic.Config.Lang["Your attempt at reviving the player did not work. Recharge and try again!"] = {
	["en"] = "Your attempt at reviving the player did not work. Recharge and try again!",
	["fr"] = "Votre tentative de faire revivre le joueur n'a pas fonctionné. Rechargez et réessayez!",
	["da"] = "Dit forsøg på at genoplive virkede ikke. Prøv igen!",
	["de"] = "Ihr Versuch, den Player wiederzubeleben, hat nicht funktioniert. Laden Sie auf und versuchen Sie es erneut!",
	["pl"] = "",
	["ru"] = "Ваша попытка возродить плеер не сработала. Пополните и попробуйте снова!",
	["es"] = "Tu intento de revivir al jugador no funcionó. ¡Recargue e intente nuevamente!",
	["pt"] = "Sua tentativa de reviver o jogador não funcionou. Recarregue e tente novamente!",
	["cn"] = "你试图让玩家复活的尝试没有成功。重新充电，再试一次!",
	["it"] = "",
	["tr"] = "Oyuncuyu canlandırma girişimin işe yaramadı. Yeniden şarj et ve tekrar dene!",
}
CH_AdvMedic.Config.Lang["A paramedic has saved you from dying!"] = {
	["en"] = "A paramedic has saved you from dying!",
	["fr"] = "Un médecin vous a sauvé de la mort!",
	["da"] = "En paramediciner har reddet dig fra at dø!",
	["de"] = "Ein Sanitäter hat dich vor dem Sterben gerettet!",
	["pl"] = "",
	["ru"] = "Фельдшер спас тебя от смерти!",
	["es"] = "¡Un paramédico te ha salvado de la muerte!",
	["pt"] = "Um paramédico salvou você de morrer!",
	["cn"] = "医护人员救了你的命!",
	["it"] = "",
	["tr"] = "Bir sağlık personeli seni ölmekten kurtardı!",
}
CH_AdvMedic.Config.Lang["You have rescued the dying person!"] = {
	["en"] = "You have rescued the dying person!",
	["fr"] = "Vous avez sauvé la personne mourante!",
	["da"] = "Du er reddet den døende spiller!",
	["de"] = "Sie haben die sterbende Person gerettet!",
	["pl"] = "",
	["ru"] = "Вы спасли умирающего!",
	["es"] = "¡Has rescatado a la persona!",
	["pt"] = "Você resgatou a pessoa que está morrendo!",
	["cn"] = "你成功救回了一个频死的玩家！",
	["it"] = "",
	["tr"] = "Ölen kişiyi kurtardın!",
}
CH_AdvMedic.Config.Lang["for responding to a life alert!"] = {
	["en"] = "for responding to a life alert!",
	["fr"] = "pour répondre à une alerte de mort!",
	["da"] = "for at reagere på en livs alarm!",
	["de"] = "für die Reaktion auf eine Lebensalarm!",
	["pl"] = "",
	["ru"] = "для ответа на предупреждение о жизни!",
	["es"] = "por responder a una alerta de vida!",
	["pt"] = "por responder a um alerta de vida!",
	["cn"] = "响应医疗请求！",
	["it"] = "",
	["tr"] = "bir yaşam belirtisine yanıt verdiğin için!",
}
CH_AdvMedic.Config.Lang["for reviving a player!"] = {
	["en"] = "for reviving a player!",
	["fr"] = "pour faire revivre un joueur!",
	["da"] = "for at genoplive en spiller!",
	["de"] = "um einen Spieler wiederzubeleben!",
	["pl"] = "",
	["ru"] = "за оживление игрока!",
	["es"] = "por revivir a un jugador!",
	["pt"] = "por reviver um jogador!",
	["cn"] = "让玩家复活！",
	["it"] = "",
	["tr"] = "bir oyuncuyu canlandırdığın için!",
}
CH_AdvMedic.Config.Lang["Your defibrillator is not fully charged!"] = {
	["en"] = "Your defibrillator is not fully charged!",
	["fr"] = "Votre défibrillateur n'est pas complètement chargé!",
	["da"] = "Din hjertestarter er ikke fuldt opladt!",
	["de"] = "Ihr Defibrillator ist nicht voll aufgeladen!",
	["pl"] = "",
	["ru"] = "Ваш дефибриллятор заряжен не полностью!",
	["es"] = "¡Su desfibrilador no está cargado completamente!",
	["pt"] = "Seu desfibrilador não está totalmente carregado!",
	["cn"] = "除颤器未充满电！",
	["it"] = "",
	["tr"] = "Defibrilatörün tam olarak şarj edilmedi!",
}
CH_AdvMedic.Config.Lang["Your defibrillator is fully charged! It can be used to revive dead players now."] = {
	["en"] = "Your defibrillator is fully charged! It can be used to revive dead players now.",
	["fr"] = "Votre défibrillateur est complètement chargé! Il peut être maintenant utilisé pour faire revivre des joueurs morts.",
	["da"] = "Din hjertestarter er fuldt opladt. Den kan bruges til at genoplive døde spillere.",
	["de"] = "Ihr Defibrillator ist voll aufgeladen! Es kann jetzt verwendet werden, um tote Spieler wiederzubeleben.",
	["pl"] = "",
	["ru"] = "Ваш дефибриллятор полностью заряжен! Теперь его можно использовать для восстановления мертвых игроков.",
	["es"] = "¡Su desfibrilador está cargado! Ya está listo para revivir jugadores muertos.",
	["pt"] = "Seu desfibrilador está totalmente carregado! Ele pode ser usado para reviver jogadores mortos agora.",
	["cn"] = "除颤器已充满电！ 现在可以用来使死者复活。",
	["it"] = "",
	["tr"] = "Defibrilatör tamamen şarj oldu! Artık ölü oyuncuları canlandırmak için kullanılabilir.",
}
CH_AdvMedic.Config.Lang["A player with a life alert has died. Their location is marked on your map!"] = {
	["en"] = "A player with a life alert has died. Their location is marked on your map!",
	["fr"] = "Un joueur avec une alerte de mort est décédé. Son emplacement est marqué sur votre carte!",
	["da"] = "En spiller med en livsvarsling er død. Deres placering er markeret på dit kort!",
	["de"] = "Ein Spieler mit einem Lebensalarm ist gestorben. Ihr Standort ist auf Ihrer Karte markiert!",
	["pl"] = "",
	["ru"] = "Игрок с предупреждением о жизни умер. Его местоположение отмечено на вашей карте!",
	["es"] = "Un jugador con una alerta de vida ha muerto. ¡Su ubicación está marcada en el mapa!",
	["pt"] = "Um jogador com um alerta de vida morreu. A localização deles está marcada no seu mapa!",
	["cn"] = "需要医疗照顾的玩家已经昏迷。他的位置在你的地图上标记出来了!",
	["it"] = "",
	["tr"] = "Yaşam belirtisi olan bir oyuncu var. Konumu haritada işaretlendi!",
}
CH_AdvMedic.Config.Lang["You can't change your team while you're unconscious!"] = {
	["en"] = "You can't change your team while you're unconscious!",
	["fr"] = "Vous ne pouvez pas changer de métier pendant que vous êtes inconscient!",
	["da"] = "Du kan ikke ændre dit hold, mens du er bevidstløs!",
	["de"] = "Du kannst dein Team nicht ändern, solange du bewusstlos bist!",
	["pl"] = "",
	["ru"] = "Вы не можете изменить свою команду, пока вы без сознания!",
	["es"] = "¡No puedes cambiar tu equipo mientras estás inconsciente!",
	["pt"] = "Você não pode mudar de equipe enquanto está inconsciente!",
	["cn"] = "当你失去意识的时候，不能改变你的职业!",
	["it"] = "",
	["tr"] = "Baygınken takımını değiştiremezsin!",
}
CH_AdvMedic.Config.Lang["You have died"] = {
	["en"] = "You have died",
	["fr"] = "Vous êtes mort",
	["da"] = "Du er død",
	["de"] = "Du bist gestorben",
	["pl"] = "",
	["ru"] = "Ты умер",
	["es"] = "Te has muerto",
	["pt"] = "Você morreu",
	["cn"] = "你昏迷了",
	["it"] = "",
	["tr"] = "Ölüyorsun",
}
CH_AdvMedic.Config.Lang["Paramedics can rescue you using defibrillators"] = {
	["en"] = "Paramedics can rescue you using defibrillators",
	["fr"] = "Les médecins peuvent vous sauver en utilisant des défibrillateurs",
	["da"] = "Paramediciner kan redde dig ved hjælp af en hjertestarter",
	["de"] = "Sanitäter können Sie mit Defibrillatoren retten",
	["pl"] = "",
	["ru"] = "Медработники могут спасти вас, используя дефибрилляторы",
	["es"] = "Los paramédicos pueden rescatarlo usando desfibriladores",
	["pt"] = "Os paramédicos podem resgatá-lo usando desfibriladores",
	["cn"] = "急救人员可以用除颤器来救你",
	["it"] = "",
	["tr"] = "Sağlık personelleri tarafından defibrilatör kullanılarak kurtulabilirsin",
}
CH_AdvMedic.Config.Lang["Click to respawn"] = {
	["en"] = "Click to respawn",
	["fr"] = "Cliquez pour réapparaître",
	["da"] = "Klik for at genoplive",
	["de"] = "Klicken Sie hier, um erneut zu erscheinen",
	["pl"] = "",
	["ru"] = "Нажмите, чтобы возродиться",
	["es"] = "Haga clic para reaparecer",
	["pt"] = "Clique para reaparecer",
	["cn"] = "单击复活（没有前生的记忆！）",
	["it"] = "",
	["tr"] = "Devam etmek için herhangi bir tuşa basın",
}
CH_AdvMedic.Config.Lang["Please wait"] = {
	["en"] = "Please wait",
	["fr"] = "Merci de patienter",
	["da"] = "Vent venligst",
	["de"] = "Warten Sie mal",
	["pl"] = "",
	["ru"] = "Пожалуйста, подождите",
	["es"] = "por favor espera",
	["pt"] = "Por favor, espere",
	["cn"] = "请稍等",
	["it"] = "",
	["tr"] = "Lütfen bekle",
}
CH_AdvMedic.Config.Lang["seconds to respawn"] = {
	["en"] = "seconds to respawn",
	["fr"] = "secondes pour réapparaître",
	["da"] = "sekunder for at genoplive",
	["de"] = "Sekunden zum Respawn",
	["pl"] = "",
	["ru"] = "секунды до возрождения",
	["es"] = "segundos para reaparecer",
	["pt"] = "segundos para reaparecer",
	["cn"] = "秒后可以强制重生（或者等待医疗人员-最多1分钟）",
	["it"] = "",
	["tr"] = "saniye sonra yeniden canlanacaksın",
}
CH_AdvMedic.Config.Lang["Distance"] = {
	["en"] = "Distance",
	["fr"] = "Distance",
	["da"] = "Afstand",
	["de"] = "Entfernung",
	["pl"] = "",
	["ru"] = "Расстояние",
	["es"] = "Distancia",
	["pt"] = "Distância",
	["cn"] = "距离",
	["it"] = "",
	["tr"] = "Mesafe",
}
CH_AdvMedic.Config.Lang["Life Alert"] = {
	["en"] = "Life Alert",
	["fr"] = "Alerte de mort",
	["da"] = "Livsvarsling",
	["de"] = "Lebensalarm",
	["pl"] = "",
	["ru"] = "Оповещение о жизни",
	["es"] = "Alerta de vida",
	["pt"] = "Alerta de vida",
	["cn"] = "生命垂危",
	["it"] = "",
	["tr"] = "Yaşam Destek Ünitesi",
}

CH_AdvMedic.Config.Lang["You have equipped a life alert!"] = {
	["en"] = "You have equipped a life alert!",
	["fr"] = "Vous avez équipé une alerte de vie!",
	["da"] = "Du har udstyret en livsalarm!",
	["de"] = "Sie haben einen Lebensalarm ausgerüstet!",
	["pl"] = "",
	["ru"] = "Вы оборудовали аварийное оповещение!",
	["es"] = "¡Has equipado una alerta de vida!",
	["pt"] = "Você equipou um alerta de vida!",
	["cn"] = "您已经装备了生命警报！",
	["it"] = "",
	["tr"] = "Bir yaşam destek ünitesi kuşandın!",
}

CH_AdvMedic.Config.Lang["You are already equipped with a life alert!"] = {
	["en"] = "You are already equipped with a life alert!",
	["fr"] = "Vous êtes déjà équipé d'une alerte vie!",
	["da"] = "Du er allerede udstyret med en livsvarsling!",
	["de"] = "Sie sind bereits mit einem Lebensalarm ausgestattet!",
	["pl"] = "",
	["ru"] = "Вы уже оснащены оповещением о жизни!",
	["es"] = "¡Ya estás equipado con una alerta de vida!",
	["pt"] = "Você já está equipado com um alerta de vida!",
	["cn"] = "您已经配备了生活警报！",
	["it"] = "",
	["tr"] = "Zaten bir yaşam destek ünitesi kuşanıldı!",
}

-- Damage & Injury System
CH_AdvMedic.Config.Lang["Your leg injury has been healed."] = {
	["en"] = "Your leg injury has been healed.",
	["fr"] = "Votre blessure à la jambe a été guérie.",
	["da"] = "Din benskade er helet.",
	["de"] = "Ihre Beinverletzung wurde geheilt.",
	["pl"] = "",
	["ru"] = "Травма вашей ноги зажила.",
	["es"] = "Su lesión en la pierna ha sido curada.",
	["pt"] = "Sua lesão na perna foi curada.",
	["cn"] = "你的腿伤已经痊愈了。",
	["it"] = "",
	["tr"] = "Bacağındaki yara iyileşti.",
}
CH_AdvMedic.Config.Lang["Your internal bleedings has been healed."] = {
	["en"] = "Your internal bleedings has been healed.",
	["fr"] = "Vos saignements internes ont été guéris.",
	["da"] = "Dine indre blødninger er blevet helbredt.",
	["de"] = "Ihre inneren Blutungen wurden geheilt.",
	["pl"] = "",
	["ru"] = "Ваши внутренние кровотечения были исцелены.",
	["es"] = "Tus hemorragias internas han sido curadas.",
	["pt"] = "Seus sangramentos internos foram curados.",
	["cn"] = "你体内的出血已经被治愈了。",
	["it"] = "",
	["tr"] = "İç kanamaların iyileşti.",
}
CH_AdvMedic.Config.Lang["Your broken arm has been healed."] = {
	["en"] = "Your broken arm has been healed.",
	["fr"] = "Votre bras cassé a été guéri.",
	["da"] = "Din brækkede arm er helbredet.",
	["de"] = "Dein gebrochener Arm wurde geheilt.",
	["pl"] = "",
	["ru"] = "Ваша сломанная рука была исцелена.",
	["es"] = "Tu brazo roto ha sido curado.",
	["pt"] = "Seu braço quebrado foi curado.",
	["cn"] = "你的手臂已经痊愈了。",
	["it"] = "",
	["tr"] = "Kırık kolun iyileşti.",
}

CH_AdvMedic.Config.Lang["Your leg has broken!"] = {
	["en"] = "Your leg has broken!",
	["fr"] = "Votre jambe s'est cassée!",
	["da"] = "Dit ben er brækket!",
	["de"] = "Dein Bein ist gebrochen!",
	["pl"] = "",
	["ru"] = "Ваша нога сломалась!",
	["es"] = "¡Tu pierna se ha roto!",
	["pt"] = "Sua perna está quebrada!",
	["cn"] = "你的腿受伤了！",
	["it"] = "",
	["tr"] = "Bacağın kırıldı!",
}
CH_AdvMedic.Config.Lang["Your arm has broken!"] = {
	["en"] = "Your arm has broken!",
	["fr"] = "Votre bras s'est cassé!",
	["da"] = "Din arm er brækket!",
	["de"] = "Dein Arm ist gebrochen!",
	["pl"] = "",
	["ru"] = "Твоя рука сломана!",
	["es"] = "¡Tu brazo se ha roto!",
	["pt"] = "Seu braço quebrou!",
	["cn"] = "你的胳膊受伤了！",
	["it"] = "",
	["tr"] = "Kolun kırıldı!",
}
CH_AdvMedic.Config.Lang["You are experiencing internal bleedings. Find a paramedic as soon as possible."] = {
	["en"] = "You are experiencing internal bleedings. Find a paramedic as soon as possible.",
	["fr"] = "Vous avez des saignements internes. Trouvez un ambulancier le plus tôt possible.",
	["da"] = "Du oplever interne blødninger. Find en læge så hurtigt som muligt.",
	["de"] = "Sie haben innere Blutungen. Finden Sie so schnell wie möglich einen Sanitäter.",
	["pl"] = "",
	["ru"] = "Вы испытываете внутренние кровотечения. Найдите фельдшера как можно скорее.",
	["es"] = "Has sufrido una emorragia interna. Encuentra a un paramédico lo antes posible.",
	["pt"] = "Você está tendo sangramentos internos. Encontre um paramédico o mais rápido possível.",
	["cn"] = "你正在流血。尽快找一个医疗人员！",
	["it"] = "",
	["tr"] = "İç kanaman var. En kısa sürede bir sağlık personeli bul.",
}
CH_AdvMedic.Config.Lang["You cannot equip this weapon with a broken arm!"] = {
	["en"] = "You cannot equip this weapon with a broken arm!",
	["fr"] = "Vous ne pouvez pas équiper cette arme d'un bras cassé!",
	["da"] = "Du kan ikke bruge dette våben med en brækket arm!",
	["de"] = "Sie können diese Waffe nicht mit einem gebrochenen Arm ausrüsten!",
	["pl"] = "",
	["ru"] = "Вы не можете вооружить это оружие сломанной рукой!",
	["es"] = "¡No puedes equipar esta arma con un brazo roto!",
	["pt"] = "Você não pode equipar esta arma com um braço quebrado!",
	["cn"] = "你手有伤的时候不能装备这个物品！",
	["it"] = "",
	["tr"] = "Bu silahı kırık kolla kuşanamazsın!",
}
--[[
CH_AdvMedic.Config.Lang[""] = {
	["en"] = "",
	["fr"] = "",
	["da"] = "",
	["de"] = "",
	["pl"] = "",
	["ru"] = "",
	["es"] = "",
	["pt"] = "",
	["cn"] = "",
	["it"] = "",
	["tr"] = "",
}
--]]