SWEP.PrintName = "Knife" -- The name of your SWEP
SWEP.Author = "Zero" -- Your name
SWEP.Instructions = "SwepInstructions" -- How do people use your SWEP?
SWEP.Contact = "YourMailAdress" -- How people should contact you if they find bugs, errors, etc
SWEP.Purpose = "WhatsThePurposeOfThisSwep" -- What is the purpose of the SWEP?
SWEP.AdminSpawnable = true -- Is the SWEP spawnable for admins?
SWEP.Spawnable = true -- Can everybody spawn this SWEP? - If you want only admins to spawn it, keep this false and admin spawnable true.
SWEP.ViewModelFOV = 64 -- How much of the weapon do you see?
SWEP.ViewModel = "models/zerochain/fruitslicerjob/weapons/fs_knife_v.mdl"
SWEP.WorldModel = "models/zerochain/fruitslicerjob/weapons/fs_knife.mdl"
SWEP.AutoSwitchTo = false -- When someone picks up the SWEP, should it automatically change to your SWEP?
SWEP.AutoSwitchFrom = true -- Should the weapon change to the a different SWEP if another SWEP is picked up?
SWEP.Slot = 1 -- Which weapon slot you want your SWEP to be in? (1 2 3 4 5 6)
SWEP.SlotPos = 1 -- Which part of that slot do you want the SWEP to be in? (1 2 3 4 5 6)
SWEP.HoldType = "knife" -- How is the SWEP held? (Pistol SMG Grenade Melee)
SWEP.FiresUnderwater = false -- Does your SWEP fire under water?
SWEP.Weight = 5 -- Set the weight of your SWEP.
SWEP.DrawCrosshair = true -- Do you want the SWEP to have a crosshair?
SWEP.Category = "Zeros FruitSlicer"
SWEP.DrawAmmo = false -- Does the ammo show up when you are using it? True / False
SWEP.ReloadSound = "sound/owningyou.wav" -- Reload sound, you can use the default ones, or you can use your own; Example; "sound/myswepreload.wav"
SWEP.base = "weapon_base" --What your weapon is based on.
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = -1
SWEP.Primary.Automatic = false
SWEP.Primary.Ammo = "none"
SWEP.Primary.Recoil = 0.5
SWEP.Primary.Delay = 0.1
SWEP.Secondary.ClipSize = -1
SWEP.Secondary.DefaultClip = -1
SWEP.Secondary.Automatic = false
SWEP.Secondary.Ammo = "none"
SWEP.Secondary.Recoil = 0.5
SWEP.Secondary.Delay = 0.1
