--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

function XeninInventory:GetItems()
  return self.Config.Items
end

function XeninInventory:CanUseInventory(ply)
  local result = hook.Run("XeninInventory.CanUseInventory", ply)

  if (result == nil or result) then
    return true
  end
end

function XeninInventory:GetItem(index)
  if self.Config.Blacklist[index] then return end

  return self.Config.Items[index] or (self.Config.WhitelistEntities[index] and self.Config.Items["base_entity"])
end

function XeninInventory:GetRarity(ent)
  if (isstring(ent) or istable(ent) or isentity(ent) and !ent.GetRarity) then
    local entClass = istable(ent) and ent.ent or ent
    if (isentity(entClass) and entClass != NULL) then
      local item = XeninInventory:GetItem(entClass:GetClass())

      if (item and item.Rarity) then
        return item.Rarity
      end

      entClass = entClass.GetWeaponClass and entClass:GetWeaponClass() or entClass:GetClass()
    end

    if (istable(ent) and ent.data and ent.data.rarity) then
      local item = XeninInventory:GetItem(ent.dropEnt)
      if (item and item.Rarity) then
        return item.Rarity
      end

      return ent.data.rarity
    end

    if (!isstring(ent) and ent.dropEnt) then
      local item = XeninInventory:GetItem(ent.dropEnt)
      if (item and item.Rarity) then
        return item.Rarity
      end
    end

    if isstring(ent) then
      local item = XeninInventory:GetItem(ent)
      if (item and item.Rarity) then
        return item.Rarity
      end
    end

    return self.Config.Rarities[entClass] or 1
  end

  if (isentity(ent) and IsValid(ent) and ent.GetRarity and ent != NULL) then
    return ent:GetRarity()
  end

  return 1
end

function XeninInventory:AddItem(index, tbl)
  self.Config.Items[index] = tbl
end

function XeninInventory:IsAdmin(ply)
  return XeninInventory.Config.Admins[ply:GetUserGroup()]
end
