--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

XeninInventory.Languages = XeninInventory.Languages or {}

function XeninInventory:CreateLanguage(name, tbl)
  self.Languages[name] = tbl
end

function XeninInventory:GetPhrase(phrase, replacement)
  local lang = XeninInventory.Config.Language
  local str = self.Languages[lang]
  if (!str) then
    str = self.Languages["English"]
  end
  str = str[phrase]
  if (!str) then
    str = self.Languages["English"][phrase]

    if (!str) then return phrase end
  end

  if replacement then
    for i, v in pairs(replacement) do
      str = str:Replace(":" .. i .. ":", v)
    end
  end

  return str
end
