--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

function XeninInventory:RequestSync()
  net.Start("XeninInventory.RequestSync")
  net.SendToServer()
end

timer.Create("XeninInventory.RequestSync", 121, 0, function()
  if IsValid(XeninInventory.Frame) then
    if XeninInventory.Frame:IsVisible() then
      return
    end
  end

  XeninInventory:RequestSync()
end)
