AddCSLuaFile()
zfs = zfs or {}

zfs.default_materials = zfs.default_materials or {}
zfs.default_materials["zfs_ui_assmble"] = Material("materials/zfruitslicer/ui/zfs_ui_assmble.png", "smooth")
zfs.default_materials["zfs_ui_desamble"] = Material("materials/zfruitslicer/ui/zfs_ui_desamble.png", "smooth")
zfs.default_materials["fs_ui_storage"] = Material("materials/zfruitslicer/ui/fs_ui_storage.png", "smooth")
zfs.default_materials["zfs_ui_productbg"] = Material("materials/zfruitslicer/ui/zfs_ui_productbg.png", "smooth")
zfs.default_materials["zfs_ui_takeacup"] = Material("materials/zfruitslicer/ui/zfs_ui_takeacup.png", "smooth")
zfs.default_materials["zfs_ui_starttheblender"] = Material("materials/zfruitslicer/ui/zfs_ui_starttheblender.png", "smooth")
zfs.default_materials["zfs_ui_slicefruit"] = Material("materials/zfruitslicer/ui/zfs_ui_slicefruit.png", "smooth")
zfs.default_materials["zfs_ui_product_hover"] = Material("materials/zfruitslicer/ui/zfs_ui_product_hover.png", "smooth")
zfs.default_materials["zfs_ui_makeproduct"] = Material("materials/zfruitslicer/ui/zfs_ui_makeproduct.png", "smooth")
zfs.default_materials["zfs_ui_chooseswetener"] = Material("materials/zfruitslicer/ui/zfs_ui_chooseswetener.png", "smooth")
zfs.default_materials["zfs_ui_sellbox_main"] = Material("materials/zfruitslicer/ui/zfs_ui_sellbox_main.png", "smooth")
zfs.default_materials["zfs_ui_sellbox_indicator"] = Material("materials/zfruitslicer/ui/zfs_ui_sellbox_indicator.png", "smooth")
zfs.default_materials["zfs_ui_sellbox_button"] = Material("materials/zfruitslicer/ui/zfs_ui_sellbox_button.png", "smooth")
zfs.default_materials["zfs_ui_sellbox_close"] = Material("materials/zfruitslicer/ui/zfs_ui_sellbox_close.png", "smooth")
zfs.default_materials["fs_ui_bar"] = Material("materials/zfruitslicer/ui/fs_ui_bar.png", "smooth")
zfs.default_materials["zfs_ui_changeprice"] = Material("materials/zfruitslicer/ui/zfs_ui_changeprice.png", "smooth")


zfs.default_colors = zfs.default_colors or {}
zfs.default_colors["white02"] = Color(255, 255, 255, 100)
zfs.default_colors["white04"] = Color(200, 200, 200)
zfs.default_colors["white06"] = Color(225, 225, 225, 255)
zfs.default_colors["black04"] = Color(25, 25, 25)
zfs.default_colors["black10"] = Color(0, 0, 0, 125)
zfs.default_colors["green01"] = Color(148, 167, 142, 255)
zfs.default_colors["green05"] = Color(155, 206, 160, 255)
zfs.default_colors["green06"] = Color(57, 181, 75, 255)
zfs.default_colors["green07"] = Color(141, 198, 63)
zfs.default_colors["green08"] = Color(25, 150, 25)
zfs.default_colors["cyan02"] = Color(0, 125, 255)
zfs.default_colors["yellow01"] = Color(230, 236, 202, 255)
zfs.default_colors["red05"] = Color(218, 28, 92, 255)
zfs.default_colors["red08"] = Color(255, 110, 102, 255)
zfs.default_colors["red09"] = Color(239, 64, 54, 255)
zfs.default_colors["red10"] = Color(255, 25, 25)
zfs.default_colors["blue03"] = Color(57, 95, 178)
