--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

include("shared.lua")

function ENT:Draw()
  self:DrawModel()

  local ply = LocalPlayer()
  local pos = self:GetPos()
  local eyePos = ply:GetPos()
  local dist = pos:Distance(eyePos)
  local alpha = math.Clamp(2500 - dist * 2.7, 0, 255)

  if (alpha <= 0) then return end

  local angle = self:GetAngles()
  local eyeAngle = ply:EyeAngles()

  angle:RotateAroundAxis(angle:Forward(), 90)
  angle:RotateAroundAxis(angle:Right(), -90)

  cam.Start3D2D(pos + self:GetUp() * 90, Angle(0, eyeAngle.y - 90, 90), 0.04)
  XeninUI:DrawNPCOverhead(self, {
    alpha = alpha,
    text = XeninInventory.Config.NPCText,
    icon = XeninInventory.Config.NPCIcon,
    sin = true,
    textOffset = -20,
    iconMargin = 50,
    color = XeninInventory.Config.NPCColor
  })
  cam.End3D2D()
end

net.Receive("XeninInventory.Bank.Open", function(len)
  if IsValid(XeninInventory.Bank) then return end
  if (!XeninInventory:CanUseInventory(LocalPlayer())) then
    LocalPlayer():XeninInventory():Message(XeninInventory:GetPhrase("ChatCommand.AccessRestricted"))

    return
  end

  local frame = vgui.Create("XeninInventory.Bank.Frame")
  frame:SetSize(ScrW(), ScrH())
  frame:Center()
  frame:MakePopup()
end)
