--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

net.Receive("XeninInventory.Slot", function(len)
  local ply = LocalPlayer()
  local inv = ply:XeninInventory()
  local id = net.ReadUInt(10)
  local tbl = net.ReadTable()


  if (table.Count(tbl) == 0) then
    tbl = nil
  end

  inv:Set(id, tbl)

  hook.Run("XeninInventory.SlotUpdateFromServer", id, tbl)
end)

net.Receive("XeninInventory.Bank.Slot", function(len)
  local ply = LocalPlayer()
  local inv = ply:XeninInventory()
  local id = net.ReadUInt(10)
  local tbl = net.ReadTable()


  if (table.Count(tbl) == 0) then
    tbl = nil
  end

  inv:Set(id, tbl, true)

  hook.Run("XeninInventory.SlotUpdateFromServer", id, tbl, true)
end)

net.Receive("XeninInventory.FullSync", function(len)
  local ply = LocalPlayer()
  local inv = ply:XeninInventory()
  local inventory = net.ReadTable()
  local bank = net.ReadTable()
  local bankRows = net.ReadUInt(8)

  inv:SetInventory(inventory)
  inv:SetBank(bank)
end)

net.Receive("XeninInventory.Message", function(len)
  local str = net.ReadString()
  local ply = LocalPlayer()
  local inv = ply:XeninInventory()
  inv:Message(str)
end)

net.Receive("XeninInventory.Admin.Search", function(len)
  local ply = LocalPlayer()
  local data = net.ReadTable()

  hook.Run("XeninInventory.Admin.Search", data)
end)

net.Receive("XeninInventory.RequestSync", function(len)
  local data = net.ReadTable()

  LocalPlayer():XeninInventory():SetInventory(data)

  hook.Run("XeninInventory.InventorySynced")
end)
