/////////////////////////
// Fantasy RP Food Mod
//https://steamcommunity.com/sharedfiles/filedetails/?id=421922332

zvm.AllowedItems.Add("eoti_food_bananas")
zvm.AllowedItems.Add("eoti_food_bloodale")
zvm.AllowedItems.Add("eoti_food_boarhead")
zvm.AllowedItems.Add("eoti_food_bread")
zvm.AllowedItems.Add("eoti_food_cheapwine")
zvm.AllowedItems.Add("eoti_food_chicken")
zvm.AllowedItems.Add("eoti_food_ciderale")
zvm.AllowedItems.Add("eoti_food_garlic")
zvm.AllowedItems.Add("eoti_food_ham")
zvm.AllowedItems.Add("eoti_food_heart")
zvm.AllowedItems.Add("eoti_food_lager")
zvm.AllowedItems.Add("eoti_food_meatstick")
zvm.AllowedItems.Add("eoti_food_mushroom")
zvm.AllowedItems.Add("eoti_food_pie")
zvm.AllowedItems.Add("eoti_food_potato")
zvm.AllowedItems.Add("eoti_food_pumpkin")
zvm.AllowedItems.Add("eoti_food_rawfish")
zvm.AllowedItems.Add("eoti_food_ribs")
zvm.AllowedItems.Add("eoti_food_rottenmeat")
zvm.AllowedItems.Add("eoti_food_saffron")
zvm.AllowedItems.Add("eoti_food_skull")
zvm.AllowedItems.Add("eoti_food_smoked_baby")
zvm.AllowedItems.Add("eoti_food_spiderhead")
zvm.AllowedItems.Add("eoti_food_winepitcher")
