/////////////////////////
// FA:S 2.0 Alpha SWEPs
//https://steamcommunity.com/sharedfiles/filedetails/?id=180507408

zvm.AllowedItems.Add("fas2_")
zvm.AllowedItems.Add("kf_")


zvm.config.PredefinedNames["kf_revolver_fas"] = ".44 Magnum"
zvm.config.PredefinedNames["kf_revolver_dual_fas"] = ".44 Magnum Dual"
zvm.config.PredefinedNames["kf_9mm_fas"] = "9mm Pistol"
zvm.config.PredefinedNames["kf_9mm_dual_fas"] = "9mm Pistol Dual"
zvm.config.PredefinedNames["kf_aa12_fas"] = "AA-12"
zvm.config.PredefinedNames["kf_aa12_gold_fas"] = "AA-12 Gold"
zvm.config.PredefinedNames["kf_ak47_fas"] = "AK-47"
zvm.config.PredefinedNames["kf_ak47_gold_fas"] = "AK-47 Gold"
zvm.config.PredefinedNames["kf_ak47_neon_fas"] = "AK-47 Neon"
zvm.config.PredefinedNames["kf_bullpup_fas"] = "Bullpup"
zvm.config.PredefinedNames["kf_knife_fas"] = "Combat Knife"
zvm.config.PredefinedNames["kf_combatshotgun_fas"] = "Combat Shotgun"
zvm.config.PredefinedNames["kf_combatshotgun_gold_fas"] = "Combat Shotgun Gold"
zvm.config.PredefinedNames["kf_dwarfaxe_fas"] = "Dwarfs Axe"
zvm.config.PredefinedNames["kf_flare_revolver_fas"] = "Flare Revolver"
zvm.config.PredefinedNames["kf_fnfal_fas"] = "FNFAL ACOG"
zvm.config.PredefinedNames["kf_handcannon_fas"] = "Handcannon"
zvm.config.PredefinedNames["kf_handcannon_dual_fas"] = "Handcannon Dual"
zvm.config.PredefinedNames["kf_handcannon_dual_gold_fas"] = "Handcannon Dual Gold"
zvm.config.PredefinedNames["kf_handcannon_gold_fas"] = "Handcannon Gold"
zvm.config.PredefinedNames["kf_hsg_shotgun_fas"] = "HSG-1 Shotgun"
zvm.config.PredefinedNames["kf_hsg_shotgun_neon_fas"] = "HSG-1 Shotgun Neon"
zvm.config.PredefinedNames["kf_kriss_fas"] = "Kriss Vector"
zvm.config.PredefinedNames["kf_kriss_neon_fas"] = "Kriss Vector Neon"
zvm.config.PredefinedNames["kf_leveraction_fas"] = "Leveraction - Rifle"
zvm.config.PredefinedNames["kf_m14_ebr_fas"] = "M14 ERB"
zvm.config.PredefinedNames["kf_grenadelauncher_fas"] = "M32"
zvm.config.PredefinedNames["kf_grenadelauncher_camo_fas"] = "M32 Camo"
zvm.config.PredefinedNames["kf_m4_fas"] = "M4"
zvm.config.PredefinedNames["kf_m4_camo_fas"] = "M4 Camo"
zvm.config.PredefinedNames["kf_m4m203_fas"] = "M4 M203"
zvm.config.PredefinedNames["kf_mac10_fas"] = "MAC-10"
zvm.config.PredefinedNames["kf_mk23_fas"] = "MK23"
zvm.config.PredefinedNames["kf_mp5m_fas"] = "MP5M"
zvm.config.PredefinedNames["kf_mp5m_camo_fas"] = "MP5M Camo"
zvm.config.PredefinedNames["kf_mp7_fas"] = "MP7M"
zvm.config.PredefinedNames["kf_scar_fas"] = "SCAR MK17"
zvm.config.PredefinedNames["kf_scar_neon_fas"] = "SCAR MK17 Neon"
zvm.config.PredefinedNames["kf_vlad9k_fas"] = "Vlad 9000"

zvm.config.PredefinedNames["fas2_ak12"] = "AK-12"
zvm.config.PredefinedNames["fas2_ak47"] = "AK-47"
zvm.config.PredefinedNames["fas2_ak74"] = "AK-74"
zvm.config.PredefinedNames["fas2_ammobox"] = "AmmoBox"
zvm.config.PredefinedNames["fas2_an94"] = "AN-94"
zvm.config.PredefinedNames["fas2_svd"] = "Dragunov SVD"
zvm.config.PredefinedNames["fas2_dv2"] = "DV2"
zvm.config.PredefinedNames["fas2_famas"] = "Famas F1"
zvm.config.PredefinedNames["fas2_g36c"] = "G36C"
zvm.config.PredefinedNames["fas2_glock20"] = "Glock-20"
zvm.config.PredefinedNames["fas2_deagle"] = "IMI Desert Eagle"
zvm.config.PredefinedNames["fas2_galil"] = "IMI Galil"
zvm.config.PredefinedNames["fas2_uzi"] = "IMI Uzi"
zvm.config.PredefinedNames["fas2_ks23"] = "KS-23"
zvm.config.PredefinedNames["fas2_mac11"] = "M11A1"
zvm.config.PredefinedNames["fas2_m14"] = "M14"
zvm.config.PredefinedNames["fas2_m16a2"] = "M16A2"
zvm.config.PredefinedNames["fas2_m1911"] = "M1911"
zvm.config.PredefinedNames["fas2_m21"] = "M21"
zvm.config.PredefinedNames["fas2_m24"] = "M24"
zvm.config.PredefinedNames["fas2_m249"] = "M249"
zvm.config.PredefinedNames["fas2_m3s90"] = "M3 Super 90"
zvm.config.PredefinedNames["fas2_m4a1"] = "M4A1"
zvm.config.PredefinedNames["fas2_m60e3"] = "M60E3"
zvm.config.PredefinedNames["fas2_m67"] = "M67"
zvm.config.PredefinedNames["fas2_m79"] = "M79"
zvm.config.PredefinedNames["fas2_m82"] = "M82"
zvm.config.PredefinedNames["fas2_machete"] = "Machete"
zvm.config.PredefinedNames["fas2_vollmer"] = "MC51B Vollmer"
zvm.config.PredefinedNames["fas2_minimi"] = "MINIMI"
zvm.config.PredefinedNames["fas2_mp5a5"] = "MP5A5"
zvm.config.PredefinedNames["fas2_mp5k"] = "MP5K"
zvm.config.PredefinedNames["fas2_mp5sd6"] = "MP5SD6"
zvm.config.PredefinedNames["fas2_ots33"] = "OTs-33 Pernach"
zvm.config.PredefinedNames["fas2_p226"] = "P226"
zvm.config.PredefinedNames["fas2_pp19"] = "PP-19 Bizon"
zvm.config.PredefinedNames["fas2_ragingbull"] = "Raging Bull"
zvm.config.PredefinedNames["fas2_rem870"] = "Remington 870"
zvm.config.PredefinedNames["fas2_rpk"] = "RPK-47"
zvm.config.PredefinedNames["fas2_rk95"] = "Sako RK-95"
zvm.config.PredefinedNames["fas2_sg550"] = "SG 550"
zvm.config.PredefinedNames["fas2_sg551"] = "SG 551"
zvm.config.PredefinedNames["fas2_sg552"] = "SG 552"
zvm.config.PredefinedNames["fas2_sks"] = "SKS"
zvm.config.PredefinedNames["fas2_sr25"] = "SR-25"
zvm.config.PredefinedNames["fas2_sterling_l2a3"] = "Sterling L2A3"
zvm.config.PredefinedNames["fas2_sterling_l34a1"] = "Sterling L34A1"
zvm.config.PredefinedNames["fas2_sterling_mk7a4"] = "Sterling MK7A4"
zvm.config.PredefinedNames["fas2_toz34"] = "TOZ-34"



zvm.config.PredefinedNames["fas2_ifak"] = "Infantry First Aid Kit"
zvm.config.PredefinedModels["fas2_ifak"] = "models/weapons/w_ifak.mdl"

zvm.config.PredefinedModels["fas2_sg550"] = "models/weapons/w_sg550.mdl"
