/////////////////////////
//TFA Starwars Galactic Weapon Reworked Pack
//https://steamcommunity.com/sharedfiles/filedetails/?id=1720373368

zvm.AllowedItems.Add("rw_sw_arc_blaster")
zvm.AllowedItems.Add("rw_sw_bowcaster")
zvm.AllowedItems.Add("rw_sw_cr2")
zvm.AllowedItems.Add("rw_sw_cr2c")
zvm.AllowedItems.Add("rw_sw_tusken_cycler")
zvm.AllowedItems.Add("rw_sw_d")
zvm.AllowedItems.Add("rw_sw_defender")
zvm.AllowedItems.Add("rw_sw_dl18")
zvm.AllowedItems.Add("rw_sw_dl44")
zvm.AllowedItems.Add("rw_sw_dt12")
zvm.AllowedItems.Add("rw_sw_dt29_4")
zvm.AllowedItems.Add("rw_sw_dt29_1")
zvm.AllowedItems.Add("rw_sw_dt29_2")
zvm.AllowedItems.Add("rw_sw_dt29_3")
zvm.AllowedItems.Add("rw_sw_dual_defender")
zvm.AllowedItems.Add("rw_sw_ee3")
zvm.AllowedItems.Add("rw_sw_ee3a")
zvm.AllowedItems.Add("rw_sw_huntershotgun")
zvm.AllowedItems.Add("rw_sw_iqa11")
zvm.AllowedItems.Add("rw_sw_iqa11c")
zvm.AllowedItems.Add("rw_sw_manda_blaster")
zvm.AllowedItems.Add("rw_sw_manda_rocket")
zvm.AllowedItems.Add("rw_sw_nt242")
zvm.AllowedItems.Add("rw_sw_nt242c")
zvm.AllowedItems.Add("rw_sw_relbyv10")
zvm.AllowedItems.Add("rw_sw_s5")
zvm.AllowedItems.Add("rw_sw_s5c")
zvm.AllowedItems.Add("rw_sw_scattershotgun")
zvm.AllowedItems.Add("rw_sw_x8")
zvm.AllowedItems.Add("rw_sw_z2")

zvm.AllowedItems.Add("rw_sw_f11a")
zvm.AllowedItems.Add("rw_sw_f11d")
zvm.AllowedItems.Add("rw_sw_fwmb10")
zvm.AllowedItems.Add("rw_sw_fwmb10k")
zvm.AllowedItems.Add("rw_sw_se44")
zvm.AllowedItems.Add("rw_sw_se44c")

zvm.AllowedItems.Add("rw_sw_cj9")
zvm.AllowedItems.Add("rw_sw_ib94")
zvm.AllowedItems.Add("rw_sw_k16")
zvm.AllowedItems.Add("rw_sw_ll30")
zvm.AllowedItems.Add("rw_sw_m57")
zvm.AllowedItems.Add("rw_sw_nn14")
zvm.AllowedItems.Add("rw_sw_relbyk23")
zvm.AllowedItems.Add("rw_sw_umb1")
zvm.AllowedItems.Add("rw_sw_westar11")

zvm.AllowedItems.Add("rw_sw_westar34")
zvm.AllowedItems.Add("rw_sw_westar35")


//zclib.RenderData.Add("rw_sw_se44", {pos = Vector(-25,-25,250)})
//zclib.RenderData.Add("rw_sw_se44c", {pos = Vector(-25,-25,325)})
zclib.RenderData.Add("rw_sw_dlt19d", {pos = Vector(0,0,35)})
